### ISSUE TITLE
Panic when downloads-dir does not exist

### ISSUE THREAD

**Issue by AckslD** [soywod/himalaya#100]
When `downloads-dir` does not exist himalaya panics with:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/msg/cli.rs:277:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
```
Maybe a more clear error-message could be printed or alternatively the folder could be created.

**Comment by AckslD** [comment]
It also panics if e.g. `~/Downloads/email` is used. Maybe it could expand the path to the home folder and not require a absolute path?

**Comment by soywod** [comment]
> Maybe it could expand the path to the home folder and not require a absolute path?

I wanted to do so, but it seems that there is no easy solution. I found a crate for this (https://github.com/netvl/shellexpand) but seems not to be maintained anymore. Let's say it's not a priority for the `v1`, but it's sth we need in the future ;)

**Comment by AckslD** [comment]
I see, yeah not a crucial thing! :)

**Comment by soywod** [comment]
I found a sneaky `unwrap` in the code that was causing this panic... I fixed it, now you have a nicer message:

```
Could not save attachment "/home/soywod/Downloadss/export-sections.xls"
 ↳ No such file or directory (os error 2)
```
