### ISSUE TITLE
Autocomplete arguments and mail ids

### ISSUE THREAD

**Issue by AckslD** [soywod/himalaya#101]
Would be nice if arguments and mail ids could be autocompleted through `<Tab>` in the cli. I've previously added this for other cli's for zsh so could give this an attempt if @soywod thinks this sounds good.

**Comment by soywod** [comment]
It sounds really good. I would love also completion there. I don't think it's a priority, I will not add to the `v1` roadmap.

**Comment by AckslD** [comment]
Completion for arguments was implemented in #99. Perhaps this could be extended by autocompleting mailboxes and mail-ids using fzf. For example, one can make it so that when typing e.g. `himalaya read **<Tab>` this opens fzf to search for the mail-id.

**Comment by soywod** [comment]
I don't think this should be *inside* himalaya. I would prefer to keep the Tab completion as "standard" as possible. If a user wants fzf then he could pipe the results to fzf, or he could set up his environnement to override the default behaviour (for eg. CTRL-r). At least we could add an entry in the wiki about it, to help user setting up such thing!

**Comment by AckslD** [comment]
That sounds reasonable!

To make such things easier for the user maybe some more formatting options would be good?
For example to do:
```
himalaya list | fzf | cut -d'|' -f1
```
doesn't look so good with the colors etc.
Maybe some helpful options could maybe for example be:
* `--no-header`: To not show the column names.
* `--no-color`: No colors.

**Comment by soywod** [comment]
This could be related to https://github.com/soywod/himalaya/issues/104. The table system needs to be improved (either by addingss tests or by replacing by a more solid crate).

**Comment by remche** [comment]
IMHO we should rely on json output for those.

`himalaya -o json list | jq '.response[].uid' | fzf`

The drawback is the `jq` dependency.

**Comment by AckslD** [comment]
Didn't know about `jq` thanks for sharing 👍

**Comment by remche** [comment]
Fish shell uid completion (needs jq):

`complete -f -c himalaya -n "__fish_seen_subcommand_from copy delete read reply" -a "(himalaya -o json list | jq -r '.response[]| [.uid, .sender + \" ✹ \" + .subject]|@tsv')"`

**Comment by soywod** [comment]
I created a new section [Tips](https://github.com/soywod/himalaya/wiki/Tips:autocomplete-uids-jq-fzf) in the wiki where I put your commands @remche, feel free to add more ;)

**Comment by soywod** [comment]
What could be great is to have dynamic completion *inside* the tool. This feature seems to be discussed @clap:

- https://github.com/clap-rs/clap/issues/568
- https://github.com/clap-rs/clap/issues/1232

**Comment by soywod** [comment]
I gather all Himalaya issues to the same [bug tracker](https://todo.sr.ht/~soywod/himalaya), so I transfer your issue [here](https://todo.sr.ht/~soywod/himalaya/22).
