### ISSUE TITLE
Expand tilde config `downloads-dir`

### ISSUE THREAD

**Issue by soywod** [soywod/himalaya#102]
https://stackoverflow.com/questions/54267608/expand-tilde-in-rust-path-idiomatically

**Comment by rottencandy** [comment]
Hi!

Thanks for making this awesome tool. I'd love to help with this,
is the plan to use [shellexpand](https://github.com/netvl/shellexpand) for this issue?

**Comment by soywod** [comment]
The lib seems not to be maintained anymore?

> Note: because I no longer have capacity to support it, I'm now looking for a new maintainer for this library. Until I'm able to find one, it is unlikely to receive new updates in any reasonably timely manner.

Anyway, I think it will fit perfectly the need, feel free to propose a PR wit this lib!

**Comment by soywod** [comment]
Tilde and env vars are now expanded for `downloads-dir` and `signature` config options. It will be packed for the next release :tada:
