### ISSUE TITLE
Connection Lost STARTTLS

### ISSUE THREAD

**Issue by yanganto** [soywod/himalaya#106]
Hi there, 

Thanks for providing this.  

I have tried to compile `himalaya` in version 0.2.6 and 0.2.4 in two different distributions of Linux with my Gmail account.

The error for me is such like this.
```
cargo run -- -l trace
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/himalaya -l trace`
[main] begin
[main] output format: PLAIN
[main] log level: TRACE
[main] browse matches
Default subcommand matched: list
Cannot connect using STARTTLS
 ↳ Connection Lost
```

Is there a good way to enable the much detail log on this?

Many thanks.

**Comment by soywod** [comment]
Logging is a recent feature that is not yet present everywhere. I try to add them each time I update the code. The imap module is not yet logged I think.

Can you share your imap settings? Did you try without STARTTLS?

**Comment by yanganto** [comment]
Here is my configure
```
name = "USER NAME"
downloads-dir = "/home/username/Downloads"
signature = "Best Regards,"

[gmail]
default = true
email = "username@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "username@gmail.com"
imap-passwd-cmd = "echo PASSWD"
imap-starttls = true

smtp-host = "smtp.gmail.com"
smtp-port = 487
smtp-login = "username@gmail.com"
smtp-passwd-cmd = "echo PASSWD"
```

If I disable the `imap-starttls`, I will got the following result

```
cargo run -- -l trace
   Compiling himalaya v0.2.6 (/home/yanganto/data/side_project/himalaya)
    Finished dev [unoptimized + debuginfo] target(s) in 3.25s
     Running `target/debug/himalaya -l trace`
[main] begin
[main] output format: PLAIN
[main] log level: TRACE
[main] browse matches
Default subcommand matched: list
Cannot login to IMAP server
 ↳ No Response: [AUTHENTICATIONFAILED] Invalid credentials (Failure)
 ```
 
 If I modify Gmail setting to allow the 低安全性應用程式存取權 (low-security application access), I will got the error like this.
 ```
 cargo run -- -l trace
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/himalaya -l trace`
[main] begin
[main] output format: PLAIN
[main] log level: TRACE
[main] browse matches
Default subcommand matched: list
Cannot login to IMAP server
 ↳ No Response: Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)
```

I think that Gmail only accept the connection with tls.
Thanks for help this.

**Comment by yanganto** [comment]
I use [trezor](https://trezor.io/) as my gpg tool and connect with `pass` command,  and there are other issues with Himalaya in this environment with the setting as readme, so echo my password on the config may make this works easier for me.  

Once this works, I am happy to contribute to Himalaya to integrate with trezor.  :)

**Comment by soywod** [comment]
It sounds like an issue with your Gmail account, did you read the wiki entry about it? https://github.com/soywod/himalaya/wiki/Configuration:note-for-gmail-users

I did not fully understand your other problems with trezor, could you give more information?

**Comment by yanganto** [comment]
My bad,  I forgot to check out the wiki.

This can works without tls, and then it still can not connect with tls.

**Comment by yanganto** [comment]
The trezor issue is that.  
If I use terzor for gpg and use following command `pass show gmail`.  It will be in an interactive cli mode,  and I need to key in the pin, and press the button several times on the trezor.  After all this step is correct, the `pass` can show the password.

And if the pass is triggered by `himalaya`,  there is no interactive cli check process, and the `himalaya` only get a empty string as password.

**Comment by soywod** [comment]
> This can works without tls, and then it still can not connect with tls.

Well, it should work with SSL/TLS. STARTTLS is not needed for Gmail, see https://support.google.com/mail/answer/7126229?hl=en.

> If I use terzor for gpg and use following command `pass show gmail`. It will be in an interactive cli mode, and I need to key in the pin, and press the button several times on the trezor. After all these steps are correct, the `pass` can show the password.

I understand better your problem. But I am afraid it is out of the scope of himalaya. You should find a way to disable the trezor interactive mode so himalaya can get your password (I can not help you there, since I don't know at all this application). I prefer to add an entry in the wiki about how to setup trezor with himalaya instead of implementing a connector. It is better to keep things simple IMO.

If you find the solution to your problem, feel free to edit the wiki for other trezor users :wink:

**Comment by yanganto** [comment]
Thanks for your help.  If I find a good solution to this, I will provide the document on the wiki page.
