### ISSUE TITLE
Don't close vim after sending email

### ISSUE THREAD

**Issue by AckslD** [soywod/himalaya#112]
After replying/sending an email the buffer is closed, which will close vim if it's the last window. It would feel more natural to me if one is taken back to the mailbox.

**Comment by soywod** [comment]
Mmmh but theoretically you should come back to the list. What actions do you do once you finished your edition? I personally `:bw`, then press `s` for `(s)end` and I reach back the email listing (which is in an other buffer).

**Comment by AckslD** [comment]
I see! I was doing `:wq` after finishing writing the message.

I tried doing `:bw` now and it seemed to bring me back to the list due to the file of the buffer and the filetype, however no emails where listed (before starting writing the message there were), see screenshot:

![gscreenshot_2021-04-19-173217](https://user-images.githubusercontent.com/23341710/115262946-481b0100-a135-11eb-9022-985a43619969.png)


Btw, I just noticed if I press `(c)ancel` after `:bw` I get:
```
Action canceled                                                                                                                                                               
Error detected while processing function himalaya#msg#draft_handle:                                                                                                           
line   20:                                                                                                                                                                    
E605: Exception not caught:  
```

**Comment by soywod** [comment]
That's why your vim was exiting. Indeed you need to kill the buffer instead. But you should see your emails, this is strange. I can not reproduce. Maybe some config / mapping interfering? Can you try to load a minimalist vim config with just Himalaya and see what happens?
 
> Btw, I just noticed if I press `(c)ancel` after `:bw` I get:
> 
> ```
> Action canceled                                                                                                                                                               
> Error detected while processing function himalaya#msg#draft_handle:                                                                                                           
> line   20:                                                                                                                                                                    
> E605: Exception not caught:  
> ```

This is normal, I did not find a way to prevent to cancel properly a `BufUnload` event:

https://github.com/soywod/himalaya/blob/28812eab06ae6a4ab1b8e7b83b6ba72838695a9a/vim/ftplugin/himalaya-msg-write.vim#L12

Do you have any idea on how to do this?

**Comment by AckslD** [comment]
What's a good minimal vim config actually? :) I'm using packer and not completely sure how to easily only load Himalaya.

Regarding the cancellation of `BufUnload`, could you add it as a group, e.g. `HimalayaUnload` and then do `autocmd! HimalayaUnload` to remove the autocommands from that group.

**Comment by soywod** [comment]
> What's a good minimal vim config actually? :) I'm using packer and not completely sure how to easily only load Himalaya.

It is a very good question :smile: I would say sth like:

```vim
" /tmp/minimal.vim

set rtp+=/path/to/himalaya/vim
```

```sh
nvim -u /tmp/minimal.vim
```

> Regarding the cancellation of `BufUnload`, could you add it as a group, e.g. `HimalayaUnload` and then do `autocmd! HimalayaUnload` to remove the autocommands from that group.

I mean, when the event `BufUnload` is triggered, it calls `himalaya#msg#draft_handle()`. Inside this function, how do I tell Vim not to exit anymore? Because `BufUnload` is called when the buffer is unloaded, which implies also when vim quits (for eg. with `:wq`). Then only way I found to prevent vim exiting is to throw an error:

https://github.com/soywod/himalaya/blob/28812eab06ae6a4ab1b8e7b83b6ba72838695a9a/vim/autoload/himalaya/msg.vim#L158

which is not sexy at all :laughing:

**Comment by AckslD** [comment]
Finally managed to have a minimal rc :P (Couldn't find a good way though, did `rm ~/.config/nvim` and `mv ~/.local/share/nvim/site/pack ~/.local/share/nvim/site/pack.bak`, have to find a better way haha). But I'm still seeing the same issue with an empty mailbox after writing a message, doing `:bw` and pressing `q`.

Regarding `BufUnload`, I now understand the issue, read to quick first. Could an option be to actually just let if onload but instead open the draft again, for example calling [`open_editor_with_draft`](https://github.com/AckslD/himalaya/blob/633e6da293eae9f6d1eb2b1562b683e9798f35ca/src/input.rs#L74) in some way. Not sure if that goes against this recommendation in the docs though:

```
BufUnload		...
				Do not switch buffers or windows!
```

**Comment by AckslD** [comment]
Btw @soywod I was playing around a bit more to see why the mailbox shows empty. This seems to happen when the buffer with the mailbox is unloaded. For example if I

* open the mailbox
* do `bnext`
* do `bprevious`
* the mailbox is incorrectly empty

which will momentarily unload the buffer with the mailbox it will then show empty when it's loaded again. This does not for example happen if the buffer is never unloaded, for example if I instead:

* open the mailbox
* open a new tab
* switch to the buffer of the mailbox
* do `:bnext`
* do `:bprevious`
* the mailbox shows normally

**Comment by soywod** [comment]
> For example if I
> 
> * open the mailbox
> * do `bnext`
> * do `bprevious`
> * the mailbox is incorrectly empty

It is crazy because when I do the same actions, I still see my mailbox! So it should really be sth with the configuration. Do you have the `set hidden` in your config?

**Comment by AckslD** [comment]
That's very strange. I don't have `set hidden`, but it also happens if I use a minimal init.vim, such as:
```
set runtimepath+=/path/to/himalaya/vim
```
What version of vim do you have?

**Comment by soywod** [comment]
I think this option is *mandatory* to not unload hidden buffers. Can you with `set hidden` in your config?

**Comment by AckslD** [comment]
Yep, that works :)

**Comment by soywod** [comment]
Great :tada: so I think it is sth to mention in the documentation.

**Comment by soywod** [comment]
Mention added in the vim README.
