### ISSUE TITLE
Feature request: batch actions on messages

### ISSUE THREAD

**Issue by remche** [soywod/himalaya#119]
It would be great if some actions could accept several UID. `copy`, `delete` and `move` especially, but `read` could be interesting too.

**Comment by soywod** [comment]
Duplicate https://github.com/soywod/himalaya/issues/85. In summary: it already works for the `delete` and `flag` commands, but it does not for the others (mostly because of the `read` command that can not accept several UIDs by design).

**Comment by remche** [comment]
Sorry I did not read the fabulous doc... will need to improve my completion though !

**Comment by soywod** [comment]
> will need to improve my completion though !

What do you mean? The completion section from the wiki?

**Comment by remche** [comment]
Yes, it does not fit well IMAP RFC sequence set syntax... Would be easier to give a whitespaced UID list.

**Comment by soywod** [comment]
Yes indeed. But there is other priorities like #109, #81, #49, #42... (in fact, all that is included in the [v1 roadmap](https://github.com/soywod/himalaya/milestone/5)). My main goal is to consolidate this tool with tests (mostly integration ones) and include essential features. Once this objective reached, we will be able to take care of details :wink:

**Comment by remche** [comment]
Totally agrees, no worry !

**Comment by soywod** [comment]
I gather all Himalaya issues to the same [bug tracker](https://todo.sr.ht/~soywod/himalaya), so I transfer your issue [here](https://todo.sr.ht/~soywod/himalaya/20).

**Comment by soywod** [comment]
The feature is ready on `develop`, it will be added to the next release #433. Commands that can be batched: `read`, `attachments`, `copy`, `move`, `delete`.
