### ISSUE TITLE
Preview email as html

### ISSUE THREAD

**Issue by soywod** [soywod/himalaya#13]

**Comment by asymmetric** [comment]
Is this closed because it's been implemented?

**Comment by soywod** [comment]
Yes, you have the argument `--mime-type|-t` with the command `read`. You can then pipe the result to `w3m` for example:

```sh
himalaya read -t html 42 | w3m -T text/html
```

It's a tip that could be added to the [wiki](https://github.com/soywod/himalaya/wiki) (the Tips section), feel free to add it!
