### ISSUE TITLE
himalaya outputs to stderr

### ISSUE THREAD

**Issue by remche** [soywod/himalaya#130]
Maybe a side effect of #126, himalaya outputs to stderr.

**Comment by soywod** [comment]
Wow I did not realize this. In fact it seems to be the default behaviour of [`env_logger`](https://docs.rs/env_logger/0.8.3/env_logger/):

> By default, `env_logger` writes logs to `stderr`

I have hard time to understand why this is the default. I will change it ASAP. Thank you to have pointed it out!

**Comment by soywod** [comment]
I set `stdout` as default. I also set up `stderr` for error logs (which was not the case anymore). I also noticed that the exit code was always 0 (even if errors occurred). I made the program return 1 in case of errors.
