### ISSUE TITLE
Sender field empty when From: header only contains email address

### ISSUE THREAD

**Issue by ropetin** [soywod/himalaya#131]
When the From: header only contains an email address the sender field in, for example, `himalaya list` is blank.  An example of a working From: header is:

`From: Joe Smith <joe.smith@example.com>`

Two examples of failing From headers are:

`From: joe.smith@example.com`
`From: <joe.smith@example.com>`

It would be nice in these cases if it defaulted to displaying the email address.

**Comment by soywod** [comment]
Indeed, only the name is shown. It could be nice to show the name if it exists, otherwise the email address. Thanks for the feedback!

**Comment by soywod** [comment]
I added the feature on master, it will be available in the next release!
