### ISSUE TITLE
Write/Reply file format on linux

### ISSUE THREAD

**Issue by remche** [soywod/himalaya#133]
May be due to recent change for windows, when sending/replying a mail, nvim on Linux display ugly  `^M` EOL.
Setting fileformat to dos makes not difference.

Note that there is only one blank line between Subject and signature.. We now have to manually add one blank line. 

```
Content-Type: text/plain; charset=utf-8^M
From: ***** <r***@***.fr>^M
To:  ^M
Subject: ^M
^M
Regards,
```

**Comment by soywod** [comment]
It is because the template was written with `writeln!` macro, which adds a `\n` at the end. Because of that, the template contained a mix of `\r\n` and `\n` which broke the file format. Thanks for the report!
