### ISSUE TITLE
Signature from file

### ISSUE THREAD

**Issue by remche** [soywod/himalaya#135]
Not a priority but it would be great if we could define signature from a file as Thunderbird does.

**Comment by soywod** [comment]
What could be nice is to check if the `signature` is a valid path. If so then the content is used as signature, otherwise the value is the signature.

**Comment by soywod** [comment]
Added on master, it should me released with the [`v0.3.2`](https://github.com/soywod/himalaya/releases/tag/v0.3.2) :tada:
