### ISSUE TITLE
Empty inbox causes error with vim plugin

### ISSUE THREAD

**Issue by geekpete** [soywod/himalaya#136]
Error is:

`Vim(let):E712: Argument of map() must be a List or Dictionary`

equivalent CLI response would be:

```
$ himalaya list
[2021-04-30T12:31:40 ERROR himalaya] The `INBOX` mailbox is empty
```

This could be handled more gracefully with "Inbox empty" or "No Messages" or equivalent output.

**Comment by soywod** [comment]
It's a good point. The other alternative I see is to show an empty table (or empty array for JSON output). What do you think?

**Comment by soywod** [comment]
In fact it was a bug, the message returned by the CLI was note taken into consideration by the vim plugin. Thanks for the feedback!
