### ISSUE TITLE
Core Dumped with Terminal Width < 63 Characters

### ISSUE THREAD

**Issue by ropetin** [soywod/himalaya#138]
Weird situation and not sure exactly how I can troubleshoot or provide any more useful data.  When running `himalaya list` in a terminal session below 64 characters width it fails with an error similar to:

```
memory allocation of 18446744073709551615 bytes failed
[1]    3491108 abort (core dumped)  himalaya
```

I would guess it is actually due to some hard-coded minimum size for the plain display because when I run `himalaya mailboxes` (a naturally thinner output) the fail cut off point is actually < 28 characters.  Additionally, when running "-o json" everything works fine regardless of terminal size.

**Comment by soywod** [comment]
Which OS do you have? I can not reproduce. It may be related to:

https://github.com/soywod/himalaya/blob/8e98895d5b55aba0bfd12ea355ec9e57c58cb80f/src/table.rs#L145-L149

**Comment by soywod** [comment]
Which version of Himalaya do you have? I tried on both Linux (Arch Linux) and macOS, I can not reproduce. No matter the size of the terminal, the `subject` column is shrunk correctly. I am not sure if the `RUST_LOG=debug` will give more information.

**Comment by paolobarbolini** [comment]
`18446744073709551615` is the result of a 64 bit unsigned integer underflowing by 1, so compiling with [`overflow-checks`](https://doc.rust-lang.org/rustc/codegen-options/index.html#overflow-checks) may reveal the source of the issue.

**Comment by soywod** [comment]
Thanks for the link, I will check it out!

>`18446744073709551615` is the result of a 64 bit unsigned integer underflowing by 1, so compiling with [`overflow-checks`](https://doc.rust-lang.org/rustc/codegen-options/index.html#overflow-checks) may reveal the source of the issue.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/soywod/himalaya/issues/138#issuecomment-830779836
>

--
Cordialement
Clément DOUIN
Développeur Full Stack
+33 6 30 34 35 47
https://soywod.me

**Comment by soywod** [comment]
Indeed it looks interesting. Thanks @paolobarbolini! The problem is I still cannot reproduce. Do you think you could try to compile with this option @ropetin? Also, did you isolated the guilty email? You can do so by increasing step by step the page size till it panics. Let us know.

**Comment by ropetin** [comment]
It happens with multiple mailboxes, so I don't think it is triggered by one specific problematic message or mailbox.  I compiled from source using the command `RUSTFLAGS="-C overflow-checks=on" cargo build --release` and when I run it with a full back trace enabled it gives some more information:

````
thread 'main' panicked at 'attempt to subtract with overflow', src/table.rs:182:46
````

I've attached the full backtrace as a file, hopefully it contains some useful troubleshooting data.
[back.txt](https://github.com/soywod/himalaya/files/6412669/back.txt)

**Comment by paolobarbolini** [comment]
So the underflow is happening [here](https://github.com/soywod/himalaya/blob/364654e1cea4652ede61a6454635dd26b62716f0/src/table.rs#L182) and the allocation [here](https://github.com/soywod/himalaya/blob/364654e1cea4652ede61a6454635dd26b62716f0/src/table.rs#L206) probably

**Comment by soywod** [comment]
> So the underflow is happening [here](https://github.com/soywod/himalaya/blob/364654e1cea4652ede61a6454635dd26b62716f0/src/table.rs#L182) and the allocation [here](https://github.com/soywod/himalaya/blob/364654e1cea4652ede61a6454635dd26b62716f0/src/table.rs#L206) probably

I still do not understand how the overflow happens here. I checked again and all cases seem to be covered. I try to test plenty of strange cases and everything works well. I cannot reproduce. @paolobarbolini do you? I am adding debug and trace logs inside the table module, maybe it will help us. I will push soon.

**Comment by soywod** [comment]
@ropetin it is on master, can you try to run himalaya with trace logs enabled and share the result (do not forget to hide sensitive data)? `RUST_LOG=trace himalaya`

**Comment by ropetin** [comment]
Output as requested.   I don't believe it is related to any particular email message.  The included output is for only one message in my inbox, which is a message from me to me, with "Test Message" in the subject and body.
[rustlog.txt](https://github.com/soywod/himalaya/files/6415503/rustlog.txt)

**Comment by soywod** [comment]
But the bug did not occur here, right? I noticed sth in the logs: `max_width: 80`. It is the default value I put if I cannot get the terminal width from `term_size` (before it was set to 0, maybe it was the reason of the panic). Are you able to reproduce since the last commit?

**Comment by ropetin** [comment]
That rustlog.txt suggests it displayed correctly, and I think I've been able to identify why.  In that case I did `RUST_LOG=trace cargo run &>! ./rustlog.txt` so I could get the output.

Running a few more tests, I pulled down a clean copy of master, built following the build instructions and if I do `himalaya list` with a small terminal size I get the same memory allocation error as originally reported.  If I do `himalaya list | less` then I get the expected output without the core dump.  So if I redirect the output somewhere else it works, but if I display it on the screen, it fails.

I've attached the tail end of the RUST_LOG from a confirmed crash, which seems to show the error more clearly.
[realcrash.txt](https://github.com/soywod/himalaya/files/6416238/realcrash.txt)

**Comment by soywod** [comment]
I got it! The program panics when there is not more space to display a shrinkable cell (so when the sum of other cells' width is bigger than the subject width). I was able to reproduce correctly. Thanks for all the time you spent on this issue. I will fix ASAP!

**Comment by soywod** [comment]
I just fixed on master (and added one more test for this use case). It will be added to the next release!
