### ISSUE TITLE
macOS release is named himalaya.exe

### ISSUE THREAD

**Issue by disrupted** [soywod/himalaya#144]
I believe executable should be without file extension

**Comment by soywod** [comment]
It is named `himalaya.exe` for historical reasons. Mostly to avoid OS specific code during installation. I will change it for the next release and let you know. Thanks for the feedback!

**Comment by soywod** [comment]
Changed in the [v0.3.2](https://github.com/soywod/himalaya/releases/tag/v0.3.2) :tada:
