### ISSUE TITLE
Homebrew Support

### ISSUE THREAD

**Issue by devanlooches** [soywod/himalaya#147]
It would be easier to install and upgrade the Himalaya cli if there was a formula in homebrew.

**Comment by soywod** [comment]
If I understood well, a new tap needs to be created with a formula. I do not know if the same GitHub repo can be used, or if a dedicated repo is needed. I would prefer to keep everything at the same place. This way, brew users can install himalaya with the command `brew install soywod/himalaya/formula`. I did not find the way to enable the short install version: `brew install himalaya` (if the name is not already taken, ofc). I really miss knowledge here, help is welcomed!

---
- https://docs.brew.sh/Formula-Cookbook
- https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by devanlooches** [comment]
I'm not really sure either how to do it. I will do some research as well. I'll let you know.

**Comment by devanlooches** [comment]
It looks like you can change the name when you do the ``brew create`` command by adding the ``--set-name <name>`` flag. Have you tried that?

**Comment by soywod** [comment]
No, I used the `brew tap-new` command, not sure about the difference. I think I will put on the side this issue, I need to dive into to really understand (or wait for someone experienced in this domain to help us). I prefer to focus on the `v1.0.0` first, then we will see. Thanks for your feedback anyway, it's a very good point!

**Comment by chenrui333** [comment]
@devanlooches @soywod I just filed a homebrew-core PR to include this great utility.

**Comment by soywod** [comment]
Thank you so much!!

**Comment by devanlooches** [comment]
I just tried installing via homebrew and it worked! So I am going to close this issue. Thank you again @chenrui333.

**Comment by chenrui333** [comment]
no problem. :)
