### ISSUE TITLE
Time out Error When sending a message

### ISSUE THREAD

**Issue by devanlooches** [soywod/himalaya#149]
Hello,
I am getting the followinng error whenever I try to send an email.
```
internal client error: timed out waiting for connection
```
Any idea what could be causing it?

**Comment by soywod** [comment]
Did you check the Wiki? There is a section about troubleshooting with Gmail: https://github.com/soywod/himalaya/wiki/Troubleshooting:gmail-credentials, it may help you.

**Comment by devanlooches** [comment]
I have made an app password for the account but even if the password is not correct, wouldn't the listing of emails not function to? For me the only part that doesn't work is sending emails.
