### ISSUE TITLE
Use state-of-the-art error library

### ISSUE THREAD

**Issue by matthiasbeyer** [soywod/himalaya#152]
Would be nice if we could move the codebase to a state-of-the-art error library, right?

I'd suggest thiserror and anyhow, given that this is a binary crate, anyhow would be sufficient IMO.

**Comment by soywod** [comment]
I checked a bit and it sounds great, let's go for anyhow!

**Comment by soywod** [comment]
I went for `anyhow`, it seemed to fit well. Thanks for your suggestion!
