### ISSUE TITLE
Couple of Small suggestions

### ISSUE THREAD

**Issue by devanlooches** [soywod/himalaya#158]
Hello,
I just wanted to let you know a couple of small suggestions that I thought of.
These are by no means a priority just something you might want to fix/add in the future.
1. Implement the ability to save more than one draft per account.
2. Make the page numbers not zero-based (as in the first page not being numbered as zero) as it is a bit confusing the first time you use them.
Thank you for building and maintaining this amazing project!

**Comment by soywod** [comment]
> 1. Implement the ability to save more than one draft per account.

This one implies to be able to choose between them. Now it only shows you the last one. It is a big feature, but sounds useful indeed!

> 2. Make the page numbers not zero-based (as in the first page not being numbered as zero) as it is a bit confusing the first time you use them.

Indeed, does not make any sense. I keep in mind for the next release ;)

Thanks for your feedback!

**Comment by devanlooches** [comment]
I just thought of a third one:
Could you add an option to disable colors.
For example having three possible values (always, auto, never) and the auto being only when the output is directed to stdout. It would be useful when your trying to direct it into a file or some other program like sed.

**Comment by soywod** [comment]
Yes indeed, it's a good point!

**Comment by soywod** [comment]
I created 3 dedicated issues not to forget them!

**Comment by devanlooches** [comment]
Great thanks!
