### ISSUE TITLE
Vim plugin: when closing write buffer I don't get the prompt

### ISSUE THREAD

**Issue by MatthiasGrandl** [soywod/himalaya#159]
Any idea what might be wrong? I am using neovim 0.5 nightly and the very latest himalaya git.
I also get a lot of errors. For example as soon as I open the Himalaya write buffer I get: `Vim(call):E121: Undefined variable: template`

or when trying to open an email with an attachment: `Vim(let):E121: Undefined variable: hasAttachment`.
If it actually manages to open an email the output is in minimized JSON and not really readable. So something seems to be very broken with my setup.

Really cool project! Hope I can sort this out.

**Comment by soywod** [comment]
> and the very latest himalaya git

I think I broke the Vim plugin with my last changes. I plan to investigate soon and to release the next version. Before we reach the v1 I would advise not to use the git version of the CLI but the latest release.

**Comment by MatthiasGrandl** [comment]
@soywod should have tested stable version before bothering you. totally works! thanks!
