### ISSUE TITLE
Add `share/application/himalaya.desktop`

### ISSUE THREAD

**Issue by toastal** [soywod/himalaya#160]
This file would be really nice to have specifically so users can leverage XDG and set `himalaya` as a default mail app

```
[Default Applications]
x-scheme-handler/mailto=himalaya.desktop;
```

as well as getting access to be chosen as the default for Firefox, `xdg-email`, etc.

- - -

I think literally this could actually be a static file @ `$PROJECT_ROOT/share/application/himalaya.desktop` and package managers can just copy it. If you don't have the bandwidth @soywod, I could probably do this (just tap "Assign").

**Comment by soywod** [comment]
It is a very good idea @toastal! I'm curious to see how you could implement this. Because Himalaya is a CLI, so it implies to launch the terminal somehow? I'm quite short in time these days, so I assign it to you. Thanks a lot for your involvement!
