### ISSUE TITLE
Integrate PGP

### ISSUE THREAD

**Issue by toastal** [soywod/himalaya#166]
[Pretty Good Privacy](https://en.wikipedia.org/wiki/Pretty_Good_Privacy), or PGP, is

> ... an encryption program that provides cryptographic privacy and authentication for data communication. PGP is used for signing, encrypting, and decrypting texts, e-mails, files, directories, and whole disk partitions and to increase the security of e-mail communications.

This is pretty common on Unix systems all of the popular git services like GitHub, GitLab, Sourchut, allow you to upload your key to have encrypted mail sent to you. I think this is pretty common, and K-9 on Android supports it, and it's recommended in a lot of circles for secure messaging.

I'm sure most here are already aware of PGP, but as a user, I would expect that when I `himalaya read #`, I would be prompted for my `gpg` unlock password if needed, and then shown the decrypted message. Currently I get nothing back. Handling 

```
Content-Type: application/octet-stream; name="message.asc"
Content-Description: OpenPGP encrypted message
```

to at least spit out the PGP message to be piped to another tool seems like an MVP. This may be a 1.0.0 blocker, I'm not sure.

**Comment by soywod** [comment]
I think this is a duplicate of #54 (not sure, do you confirm?)

**Comment by toastal** [comment]
Ah yes, it is. I searched, but I guess I missed it.
