### ISSUE TITLE
Default mailbox no longer works in vim plugin and throws error Cannot find account ``

### ISSUE THREAD

**Issue by geekpete** [soywod/himalaya#167]
Updated to latest with VimPlug, and I think this breakage is potentially related to this change:
https://github.com/soywod/himalaya/commit/e3d022720d2459262f60270fa04b32ab996efe35

I have a single default mailbox (set default true in that profile's toml section) but can no longer list messages of default mailbox with the Vim plugin using:

`:Himalaya`

which results in: 

```
Cannot find account ``
```
But loading and specifying the mailbox does work fine:

`:Himalaya mymailbox`

If this is expected behaviour then I can edit the wiki to reflect the new usage example:
https://github.com/soywod/himalaya/tree/master/vim#list-messages-view

**Comment by soywod** [comment]
Did you upgrade the CLI? Because I did some changes related to this (to select the default account when an empty string is received).

**Comment by geekpete** [comment]
Solved. Updated the vim plugin but didn't also update the main package install.
Works as expected now, thanks.
