### ISSUE TITLE
Provide html message reading within Vim plugin

### ISSUE THREAD

**Issue by geekpete** [soywod/himalaya#168]
Related: https://github.com/soywod/himalaya/issues/13

Provide a native way to configure preferring html display when reading html emails.
I guess there's probably a way to configure this already perhaps, but would be nice if it was a simple config you could flip on to enable it.

**Comment by soywod** [comment]
I was thinking about this recently. These way we could display `text/plain` parts when available, and if not it could display properly `text/html` parts based on the config (sth like `html-preview-cmd = "w3m -T text/html"`).
