### ISSUE TITLE
Support conversation/thread mode

### ISSUE THREAD

**Issue by hao-lee** [soywod/himalaya#174]
Gmail can group emails in conversations. Does himalaya have a plan to support this feature in vimplugin or CLI? Thanks.

**Comment by soywod** [comment]
Well, it could be a very good feature. I keep in mind for after the `v1.0.0`. Thanks!

**Comment by soywod** [comment]
I gather all Himalaya issues to the same [bug tracker](https://todo.sr.ht/~soywod/himalaya), so I transfer your issue [here](https://todo.sr.ht/~soywod/himalaya/18).

**Comment by soywod** [comment]
The feature has been implemented (see `himalaya envelope thread`) but is not so reliable. It will need to be improved. I did not get any feedback yet about the feature, better to open individual issues when needed.

**Comment by mattmart3** [comment]
Thanks! Do you confirm the bug tracker on source hat has been discontinued and that new issues will be kept/handled here on github?

**Comment by soywod** [comment]
Yes, all moved to GitHub for visibility and convenience. All information get be found at pimalaya.org or the GitHub organization: https://github.com/pimalaya
