### ISSUE TITLE
Vim plugin: error when replying

### ISSUE THREAD

**Issue by remche** [soywod/himalaya#176]
Replying to a message via vim plugin throws an error. I'm using neovim v0.5.0. `himalaya template forward` is working.

`Vim(call):E716: Key not present in Dictionary: "template, "\r", "", "g"), "\n"))"`

**Comment by soywod** [comment]
The plugin seems not in phase with the CLI API. There is no `template` key since the last `Template` refactor. I will fix ASAP. Thanks for the feedback!

**Comment by soywod** [comment]
Fixed by 7b046f8 :tada:
