### ISSUE TITLE
Add help wanted label

### ISSUE THREAD

**Issue by TornaxO7** [soywod/himalaya#179]
Hi! I'd like to keep helping in this project since I provided my latest pull request now. The TUI needs to wait a little bit since I'm unsure, if you're gonna accept my pull request and how to implement the way to use the local mails (if himalaya will even store some mails locally).

Where do you need more stuff to implement? I saw some issues but I got a little bit lost between them. Could you use the `help wanted` tag again to know, which one I could pick?

**Comment by TornaxO7** [comment]
Ok, I'm working on another private project now for the time being (sorry...), *but* you can add the `help wanted` tags anyhow. I might do both in parallel :D and I'm sure that I'll come back to help here :) (if it's fine for you).

**Comment by soywod** [comment]
Don't worry, you already helped so much! I will put the tag for the most needed tasks (mainly for the v1). Thanks!

**Comment by soywod** [comment]
Done!
