### ISSUE TITLE
No Response: LOGIN failed.

### ISSUE THREAD

**Issue by hebrewd** [soywod/himalaya#189]
I'm trying to setup Himalaya with an office365
I've tried to increase the log level but get the same error message, so I'm not sure the exact cause of the failure.

I can connect to the same account with aerc.

The config file for reference.
```
name = "John Dou"

[gmail]
default = true
email = "myemail@example.com"

imap-host = "outlook.office365.com"
imap-port = 993
imap-login = "myemail@example.com"
imap-passwd-cmd = "echo PASSWORD"

smtp-host = "outlook.office365.com"
smtp-port = 587
smtp-starttls = true
smtp-login = "myemail@example.com"
smtp-passwd-cmd = "echo PASSWORD"
```

**Comment by soywod** [comment]
When do you get this error? When you try to list your messages (IMAP) or when you send a message (SMTP)?

**Comment by hebrewd** [comment]
When I list the messages.

**Comment by soywod** [comment]
So it should be an IMAP issue. Did you try to remove the `@example.com` part of the `imap-login`?

**Comment by hebrewd** [comment]
I did, I get the same error message. I also tried wrong credentials on purpose and a bad host, getting the same message.
With Aerc I manage to connect to office365 with the same configurations however.

**Comment by soywod** [comment]
Did you check your Outlook 365 account? I read on some post that sometimes connections need to be accepted from the dashboard.

**Comment by hebrewd** [comment]
Yes I did, our account does allow imap connections as well.

I tried to change the credentials to fabricated ones and I get the same error message...
(It won't change to something of the authentication failed sort of error message)

**Comment by soywod** [comment]
So it mostly looks like a network issue? Hard to understand what is happening. By curiosity, did you try `imap-starttls = true`?

**Comment by hebrewd** [comment]
But I can connect just fine with a different email client, for instance aerc.
Yes I did, didn't work.

I'll try to step through the code and provide more information

**Comment by soywod** [comment]
> But I can connect just fine with a different email client, for instance aerc.

I mean, it must be a network issue related to Himalaya. Is it a pro or perso account? I will try with my perso and let you know.

**Comment by hebrewd** [comment]
Oh I apologize, I misinterpreted that. It's a pro account.
Okay, I'll look forward for the results.

**Comment by soywod** [comment]
Mmh strange. I was able to list my emails with a personal outlook account. Notice that I used a Microsoft account to connect to Outlook (my login is my gmail email), I don't know if it changes? Which type of account do you have?

**Comment by hebrewd** [comment]
I do have an enterprise office365 account.
But looking at microsoft documents they don't mention that the enterprise one have a different means to handle connections?

Can you attach your configuration file for reference? with the credentials themselves omitted of course.

**Comment by soywod** [comment]
> I do have an enterprise office365 account.

Do you have a personal account you can try with?

> Can you attach your configuration file for reference?

It is the same as yours except for the SMTP server:

```toml
[outlook]
email = "clement.douin.alias@outlook.fr"

imap-host = "outlook.office365.com"
imap-port = 993
imap-login = "clement.douin@gmail.com"
imap-passwd-cmd = "pass show outlook"

smtp-host = "smtp-mail.outlook.com"
smtp-port = 587
smtp-starttls = true
smtp-login = "clement.douin@gmail.com"
smtp-passwd-cmd = "pass show outlook"
```

**Comment by hebrewd** [comment]
Figured it out!
I've used echo for the password, my password had symbols in it.
after I've quoted the password itself, it works just fine now.
`"echo \"password\""`

The ticket may be closed, though perhaps a check for the password-cmd is due to prevent similar tickets in the future?

**Comment by soywod** [comment]
Well, let's admit that:

- Using symbols in a password is really not common (in a sense that this issue will not occur that often)
- Using `echo` for the password is not safe at all (a password manager should really be used instead, like [pass](https://www.passwordstore.org/)). In my opinion, `echo` should be used for testing purpose.

What about adding a note or a warning in the wiki (somewhere [here](https://github.com/soywod/himalaya/wiki/Configuration:config-file#account-specific-settings) I suppose)? Feel free to do so, the wiki is accessible to everyone :wink:

**Comment by hebrewd** [comment]
> Using symbols in a password is really not common (in a sense that this issue will not occur that often)  

I disagree, if you use pass for reference, it will generate passwords with symbols by default.
> Using echo for the password is not safe at all (a password manager should really be used instead, like pass). In my opinion, echo should be used for testing purpose only.

I completely agree.

However, the issue being that when the password-cmd fails, the user gets an imap error, which is confusing IMO and will lead to redundant bug reports.
As the maintainer of the project, the decision is solely up to you of course :)
Either way, thank you for an amazing tool and your prompt responses!

**Comment by soywod** [comment]
> I disagree, if you use pass for reference, it will generate passwords with symbols by default.

Oh sorry I misunderstood the word "symbol". I expected an emoji or sth similar... You meant `$` or `^`? This kind of special chars are well handled by `pass`. My password contains more than one and it works well.

> However, the issue being that when the password-cmd fails, the user gets an imap error, which is confusing IMO and will lead to redundant bug reports.

Totally agree, but how to distinguish a password containing symbols that can be interpreted by the shell (like `&`) and a real wrong password? I think the simplest is to add a tiny warning in the wiki about the usage of `echo`. I will do it during the day. Thank you for your contribution!

**Comment by soywod** [comment]
Done: https://github.com/soywod/himalaya/wiki/Configuration:config-file#account-specific-settings.
