### ISSUE TITLE
Cannot write messages through vim plugin with 'gw'

### ISSUE THREAD

**Issue by bartoszpiech** [soywod/himalaya#196]
Error in neovim: `Vim(call):E121: Undefined variable: raw`
Checked himalaya write command and everything works.
Command 'gw' does not work in neovim using himalaya.

**Comment by soywod** [comment]
There is a big PR coming very soon (https://github.com/soywod/himalaya/pull/173) and it may fix the issue. I will come back to you once the PR is merged. Thanks for your feedback!

**Comment by soywod** [comment]
Fixed in the [`v0.5.0`](https://github.com/soywod/himalaya/releases/tag/v0.5.0) :tada: (don't forget to update the CLI and the Vim plugin)
