### ISSUE TITLE
Quotes in subject are displayed as escaped characters

### ISSUE THREAD

**Issue by gabrielbdsantos** [soywod/himalaya#197]
I don't know if this is in fact an intended behavior but quotes in subject are displayed as escaped characters.
For example, instead of  `my "quoted" subject`, himalaya displays `my \"quoted\" subject` on the terminal.

**Comment by soywod** [comment]
There is a big PR coming very soon (https://github.com/soywod/himalaya/pull/173) and the behaviour may change. I will come back to you once the PR is merged. Thanks for your feedback!

**Comment by TornaxO7** [comment]
Hi! The PR has been merged now, could you please look if this issue still exists?

**Comment by gabrielbdsantos** [comment]
It seems the PR fixed it. Thanks!
