### ISSUE TITLE
Vim plugin doesnt work in neovim

### ISSUE THREAD

**Issue by timsofteng** [soywod/himalaya#200]
Hello, I noticed that plugin just don't work with neovim.
![image](https://user-images.githubusercontent.com/51912173/133674448-0dcf233b-0dfe-42f4-a6b2-58e720396865.png)

I've installed himalaya with packer:
`  use { 'soywod/himalaya' }`

Neovim 0.5
Nixos unstable

**Comment by soywod** [comment]
Duplicate #188.
