### ISSUE TITLE
Support format=flowed?

### ISSUE THREAD

**Issue by toastal** [soywod/himalaya#206]
I did not see anything about this in the code, but it seems like it may be something good to be configurable or a default. Manually cutting lines to 72 chars is obnoxious to do and is often obnoxious to read (like on my phone where 72 chars may not fit, or a smaller terminal split). It seems this is the default unless in a specific environment (like Vim + Pencil plugin with hard breaks) where the Himalaya plugin doesn't do anything "smart" with use input. Being able to render flowed quotes seems like a better UX as well. Honestly not an expert here, but it is listed under [Ettiquite](https://useplaintext.email/#etiquette) for _Use plaintext email_ as well as being 1 of 3 characteristics the site measures for recommended email clients. If configurable, `format: fixed | flowed | auto` where if the output contains line lengths over 72 characters, automatically add `format=flowed`?

I do like the concept of leverage existing tools in the editor rather than reinventing them though. Maybe the editor support is a non-issue because one should be using another plugin in tandem for rendering? If that is true and not default, it would seem a list of recommended supplemental (Neo)Vim plugins would be useful. Personally I use [Pencil](https://github.com/preservim/vim-pencil) + [Goyo](https://github.com/junegunn/goyo.vim) + [Limelight](https://github.com/junegunn/limelight.vim) to get a better reading/writing experience in my Neovim setup (for emails, blogs, whatever). 

---

https://www.ietf.org/rfc/rfc2646.txt

> A Format=Flowed message consists of zero or more paragraphs, each containing one or more flowed lines followed by one fixed line. The usual case is a series of flowed text lines with blank (empty) fixed lines between them.

>  The intent of Format=Flowed is to allow user agents to generate flowed text which is non-obnoxious when viewed as pure, raw Text/Plain (without any decoding); use of Quoted-Printable hinders this and may cause Format=Flowed to be rejected by end users.

**Comment by TornaxO7** [comment]
Might be interesting: RFC2822 recommends a max-line-length of [78 characters](https://datatracker.ietf.org/doc/html/rfc2822#section-2.1.1).

**Comment by soywod** [comment]
I'm not sure to fully understand how is it directly related to the CLI @toastal. The only moment I see this flowed format useful with the CLI is when you read an email. When you write/reply/forward it goes through your `$EDITOR`.

**Comment by soywod** [comment]
> like on my phone where 72 chars may not fit, or a smaller terminal split

@toastal are you referring to the message `list` command (the table), or the `read command? (other commands are mostly managed by the `$EDITOR`).

**Comment by toastal** [comment]
According to the spec (I think) if you go beyond 72 chars per line, you want to set the format property for readers.

But I think yes, this is mostly an editor issue. And I think terminals flow instead of wrap by default. The second paragraph suggested listing suggested plugins to achieve the effect. I think this matters to help users get into a good working state for their requirements (some mailing list require 72 chars) as well as being able to provide slightly better support if more people are using the same additional plugins.

**Comment by soywod** [comment]
So in fact everything is already there to support the flowed format, good news! The only thing I see to adjust is this arg:

https://github.com/soywod/himalaya/blob/26c2ed2a43f54a0624563566608b7b47f0c110f7/src/ui/table_arg.rs#L4-L10

It is used by list commands (`mailboxes` and `list`) and transferred to the table system to restrict its width. If none given, the size of the terminal is taken by default. I could introduce this new config entry `format` you were talking about, that takes either a fixed number, or the string "flowed" (no width restriction), or the string "auto" (the terminal size, which is the default right now and should remain the default IMO). What do you think? Do you see any other point to make himalaya compatible with the flowed format?

**Comment by soywod** [comment]
I pushed a first version on `development`. I added a `format` account config entry with this shape:

```toml
[my-account.format]
type = "flowed" # Tables are not shrunk any more

# or 

[my-account.format]
type = "auto" # Tables are shrunk to fit the terminal size (it is the default, like on master)

# or

[my-account.format]
type = "fixed"
width = 150
```
