### ISSUE TITLE
POP3 Support

### ISSUE THREAD

**Issue by DiederikVink** [soywod/himalaya#207]
I was wondering if there is any POP3 support or if there is any way that I could configure himalaya to support POP3?

**Comment by soywod** [comment]
POP3 is not supported right now, but it could be a nice feature. I keep in mind for after the `v1.0.0`. Thanks!

**Comment by soywod** [comment]
@DiederikVink could you give a bit more context about POP3? What your current setup looks like? I started to research a bit about the protocol, and it looks like emails are deleted once retrieved. Which means you need to store them manually somewhere else (I guess some `mbox` or `maildir`), right?

I'm not sure this protocol can work well with himalaya. The simplest would be to set up a POP3 to Maildir fetcher, then to configure himalaya to use this Maildir directly.

**Comment by soywod** [comment]
After searching and thinking more about POP3, I decided not to support it. Himalaya needs a backend (an email database) to operate, and POP3 is not one. I will add a note in the wiki about this.
