### ISSUE TITLE
Configuration notify-cmd

### ISSUE THREAD

**Issue by Geordinateur** [soywod/himalaya#212]
Hello, when i change notify-cmd in my config file, isn't work...
do you know why? 

`notify-cmd = "notify-send --icon='/usr/share/icons/Papirus/32x32/apps/mail-client.svg' '📫 <sender>' '<subject>'"`

**Comment by soywod** [comment]
Could you share logs from the notify command?

**Comment by Geordinateur** [comment]
Thank you, with script is good :)
