### ISSUE TITLE
need some help updating the test

### ISSUE THREAD

**Issue by chenrui333** [soywod/himalaya#222]
looks like 0.5.0 introduced some EDITOR change, and it broke [the error output of the test ](https://github.com/Homebrew/homebrew-core/pull/87071/), Can I get some help updating the test to better reflect the change? Thanks!

**Comment by soywod** [comment]
@chenrui333 I think you can replace the himalaya command by `#{bin}/himalaya 2>&1` and the expected output by `Error: cannot login to IMAP server\n\nCaused by:\n    No Response: Invalid credentials (Failure)`. Let me know.
