### ISSUE TITLE
Making the vim plugin async by using jobstart()

### ISSUE THREAD

**Issue by erietz** [soywod/himalaya#230]
Any thoughts on making this function 

https://github.com/soywod/himalaya/blob/b9a9d0e6878972071c748e5ed93353b6e486abc9/vim/autoload/himalaya/shared/cli.vim#L4

async by using `jobstart()` rather than `system()`?

Every time it is called in this file

https://github.com/soywod/himalaya/blob/b9a9d0e6878972071c748e5ed93353b6e486abc9/vim/autoload/himalaya/msg.vim#L3

vim gets blocked. I could work on a PR for this.

**Comment by erietz** [comment]
Never mind. This looks challenging since you would have to write a bunch of callback functions.

**Comment by soywod** [comment]
I finally took time to do it (1 year after :sweat_smile:), it is available on the new repo at https://git.sr.ht/~soywod/himalaya-vim.

**Comment by erietz** [comment]
On 11 Oct 2022, at 14:07 (-0500), soywod/himalaya wrote:
> I finally took time to do it (1 year after :sweat_smile:), it is available on the new repo at https://git.sr.ht/~soywod/himalaya-vim.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/soywod/himalaya/issues/230#issuecomment-1275149820
> You are receiving this because you modified the open/close state.
> 
> Message ID: ***@***.***>

Awesome, I had completely forgotten about this project.

--
Regards,

Ethan Rietz (a happy himalaya customer)
'

**Comment by soywod** [comment]
> Awesome, I had completely forgotten about this project.

It's still there, growing well :slightly_smiling_face: going toward a production-ready tool!
