### ISSUE TITLE
List accounts from the command line

### ISSUE THREAD

**Issue by dantecatalfamo** [soywod/himalaya#244]
It would be very helpful if there was a command that returned a list of accounts that are currently configured on himalaya

**Comment by TornaxO7** [comment]
Hm... is the configurator really needed? Or in other words: Is it really that user-unfriendly to configure `himalaya` throughout by editing its config file?

**Comment by soywod** [comment]
My point was just to make the tool more UX. When you just downloaded the tool for the first time and run the command `himalaya`, it could be better to propose a prompt to create your config rather than a big error message "Config file not found".

**Comment by TornaxO7** [comment]
> When you just downloaded the tool for the first time and run the command himalaya, it could be better to propose a prompt to create your config rather than a big error message "Config file not found".

This sounds reasonable to me. I've got a little question to this: How would you like to have this prompt? Should it be in a TUI or should there be always just some little prompts like
```bash
You email-address: Lol@yeetMail.com
IMAP address: <the imap-address>
Your password: <cursor>
....
```
?

**Comment by TornaxO7** [comment]
I see. So here a quick question: Which issue are you taking at the moment? Can I claim this one? I have some other question if I'm allowed to claim this issue.

**Comment by soywod** [comment]
I'm working on issues I assigned to myself (mostly related to backends), feel free to take whatever you want :)

**Comment by soywod** [comment]
> It would be very helpful if there was a command that returned a list of accounts that are currently configured on himalaya

@dantecatalfamo which kind of data did you have in mind to show? The account name? The backend used?

**Comment by dantecatalfamo** [comment]
The idea was just to have a way to select between account in the Emacs UI, the same way you can switch between mailboxes. I don't think anything more than the account identifier would be needed

**Comment by soywod** [comment]
I added a new command `accounts` that lists available accounts from the config file. The command works exactly like the `mailboxes` or the `list` commands. Here how the structure looks like:

```rust
pub struct Account {
    /// Represents the account name.
    pub name: String,

    /// Represents the backend name of the account.
    pub backend: String,

    /// Represents the default state of the account.
    pub default: bool,
}
```

 It will be packed within the next release.
