### ISSUE TITLE
Add attachments with `save` and `send` commands

### ISSUE THREAD

**Issue by soywod** [soywod/himalaya#259]
### Discussed in https://github.com/soywod/himalaya/discussions/258

<div type='discussions-op-text'>

<sup>Originally posted by **jamesaoverton** November  4, 2021</sup>
Thank you for this lovely tool. I was able to get Himalaya working without trouble, but there's one thing I want to do that I can't figure out:

I want to write a shell script that creates an email and saves it to my Drafts folder with an attached file.

I think that none of the existing commands do quite what I want:

1. `himalaya template new --subject ... > draft.mail` will create a local file with the content I want, but does not add attachments or save to Drafts
2. `himalaya --mailbox Drafts save < draft.mail` saves to Drafts, but does not add attachments
3. `himalaya write --attachment ...` creates an email with attachments and can save to Drafts, but it's interactive not scripted

I also tried `himalaya write < draft.mail` which seemed promising, but I got an endless stream of `(s)end, (e)dit, (l)ocal/(r)emote draft or (d)iscard? empty choice` lines until I pressed Ctrl-C.

Is there some combination of Himalaya commands that will let me script a draft email with attachments?

Thanks again!</div>

**Comment by soywod** [comment]
I have a working prototype where I separated the fact to save/send a raw message and the fact save/send a message from a template:

 - `himalaya save/send` allow us to send raw messages, without any treatment. Raw messages are composed of headers and parts, so there should be no attachment issue
 - `himalaya tpl save/send` allow us to send messages based on template. A template is just a more user friendly version of a message (it is what users interact with when writing/replying/forwarding messages). It only contains few headers and the text/plain body. Attachments can be added with the argument `-a|--attachment`.

**Comment by jamesaoverton** [comment]
Much appreciated!
