### ISSUE TITLE
Using Himalaya with proxy

### ISSUE THREAD

**Issue by soywod** [soywod/himalaya#264]
### Discussed in https://github.com/soywod/himalaya/discussions/263

<div type='discussions-op-text'>

<sup>Originally posted by **DhruvaSambrani** November 18, 2021</sup>
My institute has a manual proxy setting that must be set for applications to connect to the internet. This has been a recent development, and all cli email clients seem to stop connecting to the email servers.

For neomutt, there was a closed issue for no one being interested in implementing the feature, and I have opened an issue for aerc. 

Himalaya too doesn't seem to connect to email servers, despite having set http_proxy and https_proxy settings in /etc/environment. All other applications, like curl, work as expected. So, is this a lacking feature in Himalaya (and other clients) or does the NetAdmin have to open some port for email clients to connect?</div>

**Comment by DhruvaSambrani** [comment]
@soywod So updates about the proxy. I think the NetAdmin has opened the IMAP, and himalaya works (so does aerc, did not check neomutt) without any changes at all. I think you can close this issue then?

**Comment by soywod** [comment]
> I think the NetAdmin has opened the IMAP port, and himalaya works

Glad to heart that!

> I think you can close this issue then?

I think it could be a good feature after the `v1.0.0`. Thunderbird seems to be able to propose HTTP, HTTPS, SOCKS v4 and v5 proxies:

![screenshot](https://user-images.githubusercontent.com/10437171/143442678-f99fb61d-bd8a-49a1-ad94-fa5e642a073b.jpeg)

**Comment by soywod** [comment]
~~I gather all Himalaya issues to the same [bug tracker](https://todo.sr.ht/~soywod/himalaya), so I transfer your issue [here](https://todo.sr.ht/~soywod/himalaya/17).~~

**Comment by soywod** [comment]
5 years after, the feature finally lands 🎉 it supports SOCKS5 and HTTP CONNECT protocols, natively from standard env vars.
