### ISSUE TITLE
Himalaya lists oldest emails first

### ISSUE THREAD

**Issue by codeinred** [soywod/himalaya#265]
For some reason, Himalaya is listing the oldest emails first when I use it. I've searched, but I can't find any option to change this. 

![image](https://user-images.githubusercontent.com/36810712/143787524-11cc3102-553c-4f31-b854-1d2664ac3a1b.png)

This is my Himalaya config file (with personal information redacted). I'm using ProtonMail Bridge, which is why the host is configured to 127.0.0.1.

Any suggestions or guidance would be appreciated.
```
name = <redacted>
downloads-dir = "~/Downloads/email"
signature = <redacted>

[protonmail]
default = true
email = <redacted>
default-page-size = 25

imap-host = "127.0.0.1"
imap-port = 1143
imap-login = <redacted>
imap-passwd-cmd = <redacted>
imap-starttls = true
imap-insecure = true

smtp-host = "127.0.0.1"
smtp-port = 1025
smtp-login = <redacted>
smtp-passwd-cmd = <redacted>
smtp-starttls = true
smtp-insecure = true
```

**Comment by soywod** [comment]
The `list` command (which does a [`FETCH`](https://datatracker.ietf.org/doc/html/rfc3501#section-6.4.5) IMAP command behind the scene, nothing more) sorts by sequence number (the `ID` column). If we take the first email in your list (the one with sequence id at `299`), it is the most recent email of your targeted mailbox but not in term of email date. When an email arrives in a mailbox (not matter if it is a new one dropped by a SMTP provider or if you moved it from another mailbox), it receives a new sequence number (which becomes the biggest of the mailbox). Did you reorganized your emails recently?
For me the behaviour is the expected one. I can propose you to either:
- reorganize your email by date (so the will have the correct sequence number)
- wait for #34 (it should allow us to sort emails other than by sequence number, see [RFC](https://datatracker.ietf.org/doc/html/rfc5256#section-3))
