### ISSUE TITLE
bug: Vim plugin not able to delete messages

### ISSUE THREAD

**Issue by jakeschurch** [soywod/himalaya#268]
Hi there,

seem to be having an issue when it comes to deleting messages. Currently using both 0.5.1 versions of himalaya cli / vim plugin.  

Changing https://github.com/soywod/himalaya/blob/f9775ae8afff236c7f948d4d2e0014146dcaed0e/vim/autoload/himalaya/msg.vim#L339 to below seems to have fixed my issue. Apologies for not being well-versed in lua / vimscript.

```lua
return join(map(range(a:from, a:to), 's:trim(split(getline(v:val), " ")[0])'), ",") 
```

**Comment by jakeschurch** [comment]
further note: Message deletion prompt would initially respond with full focused line, including | delim and fields such as subject, sender, etc.

**Comment by javiermateos** [comment]
I had the same issue and I can confirm that the solution of @jakeschurch worked for me too.

**Comment by toastal** [comment]
Yes I got this error as well

```
error: Found argument '│' which wasn't expected, or isn't valid in this context
USAGE:
    himalaya delete <SEQ>
For more information try --help
```

**Comment by edlandm** [comment]
For what it's worth, I added this fix locally. I'm guessing that the original column-delimiter was the ascii pipe-character, but it was later changed to a nicer-looking unicode character.
I created one new function, get_msg_id that is then called by both `get_focused_msg_id` and `get_focused_msg_ids`.
```vim
function! s:get_msg_id(line)
  return trim(split(a:line, "│")[0])
endfunction

function! s:get_focused_msg_id()
  try
    return s:get_msg_id(getline("."))
  catch
    throw "message not found"
  endtry
endfunction

function! s:get_focused_msg_ids(from, to)
  try
    return join(map(range(a:from, a:to), "s:get_msg_id(getline(v:val))"), ",")
  catch
    throw "messages not found"
  endtry
endfunction

```

**Comment by soywod** [comment]
The issue has been fixed on the `development` branch (https://github.com/soywod/himalaya/pull/247), it should be merged on `master` for the next release, I let you know!
