### ISSUE TITLE
Non-interactive API for `write` and `reply`

### ISSUE THREAD

**Issue by dantecatalfamo** [soywod/himalaya#270]
Currently a couple of the methods used for sending mail like `write` and `reply` rely on the users being able to interact directly with the terminal. This makes it difficult to integrate with Emacs where the goal is to keep everything integrated with the editor. Would it be possible to add a non-interactive API for these functions?

**Comment by soywod** [comment]
These functions already exist (you can check the Vim plugin for
inspiration). Check `save` and `send` commands in the wiki
https://github.com/soywod/himalaya/wiki. Let me know if it is what you
were looking for!
