### ISSUE TITLE
library not found for -liconv

### ISSUE THREAD

**Issue by henry-hz** [soywod/himalaya#272]
Dears maintainers,

I am having this error when trying to run 'nix run' in Macos [amd64]:
```
       >   = note: ld: library not found for -liconv
       >           clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
       >
       >
       > error: aborting due to previous error
       >
```

I found similar errors in other scenarios [see below], but still struggling to solve...
thanks
hh

https://github.com/wildsebastian/nixpkgs/blob/15347ac96526dbb8fab5917573b63692884a43fa/pkgs/tools/admin/procs/default.nix

https://github.com/wildsebastian/nixpkgs/commit/15347ac96526dbb8fab5917573b63692884a43fa

**Comment by soywod** [comment]
I'm still learning Nix, I will not be able to help (for now). If someone
else with more experience in this domain can have a look?

**Comment by soywod** [comment]
I was not able to run the command `nix run` either (I got another error). I fixed mine [here](https://github.com/soywod/himalaya/pull/274/files), could you please try locally (branch name: `nix-run-issue`) if it fixes also your issue?

**Comment by soywod** [comment]
I replaced `cargo2nix` by `naersk` and it seems to fix my issue. Feel free to reopen if your issue persists!
