### ISSUE TITLE
Installation via cargo

### ISSUE THREAD

**Issue by mborejdo** [soywod/himalaya#273]
First of all thanks for this little awesome tool. That's exactly what I was looking for: a rust based, windows compatible email cli-client. Finally.
I wonder, if it would be possible to install himalaya via cargo. Currently I am getting
```
 Updating git submodule `git@github.com:soywod/himalaya.wiki.git`
error: failed to update submodule `wiki`

Caused by:
  failed to fetch submodule `wiki` from git@github.com:soywod/himalaya.wiki.git
```

**Comment by soywod** [comment]
What do you mean by installing himalaya via cargo, from the sources or
as a rust lib?

From sources, you can find the procedure in the wiki. A `git clone
https://github.com/soywod/himalaya.git` followed by a `cargo build` or
`cargo run` should work.

As a Rust lib it is not possible yet (I plan to do it in the future).

On 19/12/2021 21:37, Michael Borejdo wrote:
> First of all thanks for this little awesome tool. That's exactly what I was looking for: a rust based, windows compatible email cli-client. Finally.
> I wonder, if it would be possible to install himalaya via cargo. Currently I am getting
>
>  Updating git submodule ***@***.***:soywod/himalaya.wiki.git`
> error: failed to update submodule `wiki`
>
> Caused by:
>   failed to fetch submodule `wiki` from ***@***.***:soywod/himalaya.wiki.git
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
>

-- 
Cordialement
Clément DOUIN
Développeur Web Full-Stack
https://soywod.me

**Comment by mborejdo** [comment]
usually I want to compile the binaries myself using rustup. So I would like to `cargo install himalaya --git https://github.com/soywod/himalaya`

**Comment by soywod** [comment]
Ah, I see. I've never tried this, maybe there is a problem with the wiki
submodule. It is not the first time I have trouble with it, I guess I
will remove it. I let you know!

On 20/12/2021 04:27, Michael Borejdo wrote:
> usually I want to compile the binaries myself using rustup. So I would like to cargo install himalaya --git https://github.com/soywod/himalaya
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.
>

-- 
Cordialement
Clément DOUIN
Développeur Web Full-Stack
https://soywod.me

**Comment by soywod** [comment]
I just removed the wiki git submodule, you should be able to install himalaya from `cargo install` starting from the next release (I let you know when I release it).

**Comment by soywod** [comment]
Could you try again with the new version?

**Comment by soywod** [comment]
I will try to see if I can publish himalaya to cargo registry, so cargo users can do `cargo install himalaya`.
