### ISSUE TITLE
Error: cannot fetch messages within range "{}"

### ISSUE THREAD

**Issue by JostBrand** [soywod/himalaya#275]
I want to use himalaya with 2 accounts: 
1 works for and this one does not:

```
[mymain]
default = true
email = "name@myhomepage.xyz"

imap-host = "mail.myhomepage.xyz"
imap-port = 143
imap-starttls = true
imap-login = "name@myhomepage.xyz"
imap-passwd-cmd = "pass show myhomepage.xyz/jost@myhomepage.xyz"

smtp-host = "smtp.web.de"
smtp-port = 587
smtp-starttls = true
smtp-login = "jost@jostbrandstetter.xyz"
smtp-passwd-cmd = "pass show myhomepage.xyz/name@myhomepage.xyz"
```
I get the error msg:

Error: cannot fetch messages within range "{}"

Caused by:
    Unable to parse status response "{}"

I see the mailboxes but just not the messages

**Comment by soywod** [comment]
It looks like the IMAP server returns a bad response. Did you try to
activate the debug mode to have more information? This account works
well elsewhere?

-- 
Cordialement
Clément DOUIN
Développeur Web Full-Stack
https://soywod.me

**Comment by JostBrand** [comment]
These server settings work on Thunderbird and K9Mail (Android). 

I ran the command with the -l debug options but the output is the same.

**Comment by soywod** [comment]
Duplicate https://github.com/soywod/himalaya/issues/276.
