### ISSUE TITLE
Squeeze multiple blank lines

### ISSUE THREAD

**Issue by palb91** [soywod/himalaya#280]
Some mails have an insane amount of blank lines between two paragraph (sometimes 10-15 empty lines between two paragraphs) when I run `himalaya read n`.
I pipe them in `cat -s` for now, but I don't do it by default and it's a bit annoying to do it twice.

**Comment by soywod** [comment]
It is strange, because himalaya already tries to "purify" HTML parts:

https://github.com/soywod/himalaya/blob/f9775ae8afff236c7f948d4d2e0014146dcaed0e/src/domain/msg/msg_entity.rs#L99-L114

Could you share the raw message so we can why it is not purified? Don't forget to skip headers and/or sensitive data.

**Comment by palb91** [comment]
Well, I found one. 
`himalaya read 18 >out.txt` : [out.txt](https://github.com/soywod/himalaya/files/7965759/out.txt)

I opened the result in `vim`, it appears that most of the blank lines contains spaces, so maybe you could remove trailing spaces too before merging newlines ?

Rust is quite complicated to read for me, but based on the code you shared maybe modifying (l.109) `r"(\r?\n ?){2,}"` with `r"(\r?\n *){2,}"` could do the job.

**Comment by soywod** [comment]
Does the original message contain a HTML part, or just a text plain (or both)? I try to figure out if all those blanks are visible in the HTML or the plain text format. If there is a HTML part, then could you try to force the type (with `himalaya read -t html 18`) and see?

**Comment by soywod** [comment]
In fact, could you share the full raw msg (with `himalaya read --raw 18 >out.txt`) so I can see all the parts?

**Comment by palb91** [comment]
[out.txt](https://github.com/soywod/himalaya/files/7978591/out.txt)
Yes, with headers now, I forgot that part.

**Comment by soywod** [comment]
Great, I confirm that it is the `text/plain` part that contains all this horrible spaces. It explains why you see them, because for now I only treat `text/html` parts. It is the first time I encounter a bad `text/plain`. I guess I will apply the same rules for both!

**Comment by soywod** [comment]
I fixed the issue on `development`, it will be on `master` for the next release. I let you know!

**Comment by palb91** [comment]
Great! Thanks.

**Comment by palb91** [comment]
Well, I just checked the development branch, it works well with the sample I provided, but I found two mails that keep the same behavior. The main difference is that there are tabulation instead of spaces in empty lines.
I tried the following in msg_entity.rs (l.109 and 118) and it worked:

```diff
-            let sanitized_html = Regex::new(r"(\r?\n *){2,}")
+            let sanitized_html = Regex::new(r"(\r?\n\s*){2,}")
```

Or maybe `[\t ]*` would be more reliable?

**Comment by soywod** [comment]
`\s` is not specific enough, since it can be a carriage return also. `[\t ]*` sounds like a better approach, I just pushed it. Let me know if it's better!

**Comment by palb91** [comment]
It's almost perfect, but there is still some bad handling, or maybe the problem does not come from `himalaya` but from the shitty email itself.

In webmail the mail is printed correctly:
<img src="https://user-images.githubusercontent.com/29063375/152009550-98992bc8-b058-4881-a9ae-628974e7d4b0.png" width="450px"/>

With `himalaya`, first there is this strange CSS which is printed (another issue), and there are still those ugly tabs.
[out.raw.txt](https://github.com/soywod/himalaya/files/7980213/out.raw.txt)
[out.txt](https://github.com/soywod/himalaya/files/7980080/out.txt)

I won't blame you if you consider it a problem with the mail and not `himalaya` 🙃

**Comment by soywod** [comment]
I updated the regex, I think it is the maximum I can do :rofl: it could be great to write tests for this part. About CSS I can do nothing, it is really included in the `text/plain` part (how dumb it is…). And I can't really remove it, how to distinguish fake dumb CSS from real CSS written in a message?

**Comment by palb91** [comment]
> I updated the regex, I think it is the maximum I can do 🤣

Well, thank you for this, it is readable without too much efforts now.

> about the CSS

Yeah, I just checked with other tools or config that print only plaintext, it's definitively a bad formated mail.
