### ISSUE TITLE
Improve attachments command

### ISSUE THREAD

**Issue by palb91** [soywod/himalaya#281]
`himalaya attachments n` currently downloads attachments and displays the number of files downloaded.
I'd like to see the file names in output, that would help to find them in big folders, eventually with a prompt to change the filename if it already exists in the downloads-dir.

**Comment by soywod** [comment]
The `attachments` command is one of the most legacy one. It really needs a refactor to be more UX and usable. But it is clearly not a priority, there is some much to do before. I keep in mind for later (after the `v1` I guess). Feel free to propose a PR!

For now, the only way for you to see the downloaded attachment names is to activate logs. Something like `RUST_LOG=debug himalaya attachments n`. See https://github.com/soywod/himalaya/wiki/Tips:debug-and-logs for more information.

**Comment by palb91** [comment]
Thanks for the tip, I'll keep it in mind.

> Feel free to propose a PR!

I'm not a developer myself, I'll see what I can do with my limited knowledges.
