### ISSUE TITLE
RFC822 multiple recipients not working

### ISSUE THREAD

**Issue by sbromberger** [soywod/himalaya#288]
In `himalaya write`, I've tried specifying multiple recipients separated by commas: `To: foo@invalid.com, bar@invalid.com` - this results in an email sent to `foo@` but not to `bar@`. What's the correct way of specifying multiple recipients?

Thanks!

**Comment by sbromberger** [comment]
I think you should allow whitespace between the comma and the next address. [RFC822 Appendix A.1.5](https://datatracker.ietf.org/doc/html/rfc822#appendix-A.1.5) seems to suggest that even newlines are acceptable.

**Comment by soywod** [comment]
> I think you should allow whitespace between the comma and the next address. [RFC822 Appendix A.1.5](https://datatracker.ietf.org/doc/html/rfc822#appendix-A.1.5) seems to suggest that even newlines are acceptable.

Yes definitely, but my point was more about what to do when there is *really* a bad email address (sth like `bad#addr@@com`). I think I will add a warning in the logs and skip the address, so the email can still be sent.

**Comment by sbromberger** [comment]
> my point was more about what to do when there is really a bad email address

Oh, sorry, I missed that. I think either action is fine as long as the sender is notified that delivery was not attempted.

**Comment by soywod** [comment]
I fixed the issue on `development`, it will be shipped with the next release! I opted for the failure rather than warning. At least, things are clear: you cannot send a message with a wrong recipient. I also added more logs.

**Comment by sbromberger** [comment]
Thank you so much. This tool is now my go-to for reading email in the console. I really appreciate all your efforts here.

**Comment by sbromberger** [comment]
(and, having thought about it some more, I think that a failure is the right thing to do - especially for folks who are scripting or automating using himalaya.)

**Comment by sbromberger** [comment]
Confirmed fixed on `development` branch. Thanks!
