### ISSUE TITLE
Enhancement request: move multiple messages

### ISSUE THREAD

**Issue by sbromberger** [soywod/himalaya#291]
Would it be possible to add a range of messages to `himalaya move`? That is,
`himalaya move 1-10 Archive` or `himalaya move 1,3,6 Archive`

The challenge is that the indices get renumbered after each move, but perhaps the program can keep track of that.

**Comment by soywod** [comment]
Duplicate https://github.com/soywod/himalaya/issues/119. It could be a nice feature indeed, but not so easy to set up!
