### ISSUE TITLE
Mailbox picker provider and custom folders

### ISSUE THREAD

**Issue by VolkovIlia** [soywod/himalaya#298]
How to use mailbox picker provider? Did not find any information about bindings and command...

Also is it any function to create custom folders (or tags) to sort mails?

**Comment by soywod** [comment]
Are you talking about the Vim plugin? If so then you can just follow this guide: https://github.com/soywod/himalaya/tree/master/vim#mailbox-picker-provider.

**Comment by VolkovIlia** [comment]
> Are you talking about the Vim plugin? If so then you can just follow this guide: https://github.com/soywod/himalaya/tree/master/vim#mailbox-picker-provider.

Yeap, I saw it, but did not figure out bindings or commands to start telescope or fzf search

**Comment by soywod** [comment]
It is when you change the current mailbox (see https://github.com/soywod/himalaya/tree/master/vim#list-messages-view, binding `gm` by default).

**Comment by VolkovIlia** [comment]
Thx!

**Comment by VolkovIlia** [comment]
What about creating sorting mail by custom folders/labels or tags? Is it any functions?

**Comment by soywod** [comment]
The IMAP SORT command has been merged not so long time ago https://github.com/soywod/himalaya/issues/34, it is not yet available in the vim plugin. I invite you to open an other issue for this purpose!
