### ISSUE TITLE
No tilde expansion in `maildir-dir`

### ISSUE THREAD

**Issue by wylfen** [soywod/himalaya#305]
It seems that even though the [example config](https://github.com/soywod/himalaya/wiki/Configuration:config-file#example) has
```toml
maildir-dir = "~/Maildir"
```
shell expansion is not yet supported in the `maildir-dir` variable.

**Comment by soywod** [comment]
Indeed, the tilde (and env vars) are not expanded in the `maildir-dir`. Although it should not be complicated to set up, it has already been done for the `downloads-dir`: https://github.com/soywod/himalaya/blob/158bc86cfaa1ad3ff2b9fb9ec842c7f941e61042/src/config/account_config.rs#L91

**Comment by soywod** [comment]
You can take with great pleasure! Happy to see you back :wink: (don't forget to start from the `development` branch).

**Comment by soywod** [comment]
The bug has been fixed by @TornaxO7 on the `development` branch, it will be shipped with the next release!
