### ISSUE TITLE
Unknown Command: SORT

### ISSUE THREAD

**Issue by Moncheeta** [soywod/himalaya#308]
I did all the install steps including the 2FA password but I get this error when starting himalaya.

Error: cannot search in "INBOX" with query "all"

Caused by:
Bad Response: Unknown Command: SORT

What am I missing?

**Comment by soywod** [comment]
What is your email provider? It looks like it does not support the IMAP SORT command. Since the last release, the "list" command relies on SORT which is potentially a mistake.

**Comment by Moncheeta** [comment]
I'm using Gmail.

**Comment by soywod** [comment]
I see. I guess I will have to remove this SORT dependency. I will fix this for the next release. Thank you!

**Comment by drahnr** [comment]
Can confirm, 0.5.5 works.

**Comment by soywod** [comment]
Fixed on `development`, it should be fixed for the next release!
