### ISSUE TITLE
Cannot Append Message to Sent

### ISSUE THREAD

**Issue by Moncheeta** [soywod/himalaya#313]
When I used Himalaya on the development branch, I compiled it and ran the executable in target/release. "./himalaya write". Then, I composed my message within vim and did :wq. I typed 's' for the user prompt. Then, I got this error. (I'm using Gmail)

```
Error: cannot append message to "Sent"

Caused by:
    No Response: Folder doesn't exist. (Failure)
```

**Comment by soywod** [comment]
I would not advise to use de `development` branch unless you really want to try a specific feature, or if you want to contribute. Himalaya is unstable by default (it did not reach the `v1` yet), the `development` branch can be *really* unstable. Also, you can have some breaking changes that are not yet listed in the changelog.

About your problem, it looks like gmail does not recognize the default `Sent` folder. Could you check if you see `Sent` in your mailboxes (`himalaya mailboxes`)?

**Comment by Moncheeta** [comment]
I don't have a "Sent" folder, but I do have a "Sent Mail" folder. I'm using the development branch because of my previous issue ("Unknown command SORT").

**Comment by soywod** [comment]
> I'm using the development branch because of my previous issue ("Unknown command SORT").

Oh, I see. Then I'm sorry, I misunderstood.

> I don't have a "Sent" folder, but I do have a "Sent Mail" folder.

On the `development` branch you can create mailbox aliases. For you specific case, you could add in you account's config:

```toml
[your-account]
...
[your-account.mailboxes]
sent = "Sent Mail"
```

**Comment by Moncheeta** [comment]
I found the issue. It was my fault. The response from "./himalaya mailboxes" was "[Gmail]/Sent Mail" not "Sent Mail". I didn't know if I had to copy the whole thing. Thank you!

**Comment by Moncheeta** [comment]
# The output of ./himalaya mailboxes

```
DELIM │NAME              │ATTRIBUTES                 
/     │INBOX             │\HasNoChildren             
/     │[Gmail]           │\HasChildren, NoSelect     
/     │[Gmail]/All Mail  │\All, \HasNoChildren       
/     │[Gmail]/Drafts    │\Drafts, \HasNoChildren    
/     │[Gmail]/Important │\HasNoChildren, \Important 
/     │[Gmail]/Sent Mail │\HasNoChildren, \Sent      
/     │[Gmail]/Spam      │\HasNoChildren, \Junk      
/     │[Gmail]/Starred   │\Flagged, \HasNoChildren   
/     │[Gmail]/Trash     │\HasNoChildren, \Trash 
```

My config:
```
[gmail.mailboxes]
sent = "[Gmail]/Sent Mail"
```
