### ISSUE TITLE
Improve doc related to message id

### ISSUE THREAD

**Issue by Moncheeta** [soywod/himalaya#316]
I tried doing "./himalaya read (the name of the email)", but it returns 'Error: cannot fetch messages "(the name of the email)" Caused by: Bad Response: Could not parse command' The same thing happens when I try to reply to an email. 

What am I doing wrong? (I'm new to Himalaya)

**Comment by Moncheeta** [comment]
Sorry! I shortly found out that the <SEQ> means the ID. Could you update the help command to make it a little more helpful?

**Comment by soywod** [comment]
Sure, I can do this for the next release.
