### ISSUE TITLE
Mailboxes JSON API format broke

### ISSUE THREAD

**Issue by JackTheMico** [soywod/himalaya#331]
Hi, I'm using the latest LunarVim and met this error after I pressed `gm` on Himalaya page.
![image](https://user-images.githubusercontent.com/19216598/157200163-aea1c3fb-6684-4dd2-80b6-2fb3d6782720.png)

I checked that I'm using the latest version for both the plugin and himalaya-cli
![image](https://user-images.githubusercontent.com/19216598/157200414-03cee70e-7715-46da-8d3d-08b1eced15e9.png)

I have no idea what's going on here, the config of this plugin is like:
```
vim.g.himalaya_mailbox_picker = 'native'
vim.g.himalaya_telescope_preview_enabled = 1
```
Let me know if there were any more infomation that you need to know, great project by the way.:thumbsup:

**Comment by soywod** [comment]
I just tried on neovim `v0.5.1` and I cannot reproduce your bug. The native mailbox picker works as expected. Could it be related to the neovim version? LunarVim works only on `v0.6.1+`. I will try on a newer version of neovim and let you know.

**Comment by soywod** [comment]
I just tried with the nightly version `v0.7.0` and I still cannot reproduce. Could you run the command `himalaya mboxes` in your terminal and see if sth is wrong with your mailboxes?

**Comment by JackTheMico** [comment]
Thanks for reply so quickly, I'm using neovim `v0.6.1` and `himalaya mboxes` works as expected in terminal.
I use a workaround from #188 in my config.lua
```
vim.o.runtimepath = vim.o.runtimepath..',~/.local/share/lunarvim/site/pack/packer/start/himalaya/vim'
```
![image](https://user-images.githubusercontent.com/19216598/157355003-28f11dd4-5452-4109-9ef3-854d29e09c8a.png)

**Comment by soywod** [comment]
Everything looks normal. I still cannot reproduce :disappointed: I'm afraid I will not be able to help without reproducing it. Do you think you could setup a minimal reproducible environment (himalaya version, vim config) so I can at least reproduce it on my own and start investigating the bug?

**Comment by JackTheMico** [comment]
I have built an environment on my personal server for you to reproduce and investigate. I sent an email with details to your email account, it contains everything you need to login.

**Comment by soywod** [comment]
> I have built an environment on my personal server for you to reproduce and investigate.

I was able to find the cause of the issue thanks to your environment, thank you! You can disable my account. I was not able to reproduce locally because the himalaya executable used by the vim plugin was not the right one (an old version). By fixing it I was able to reproduce the same error as yours. In fact there is a regression on the himalaya JSON API, the structure has changed. I will fix for the next release!

**Comment by soywod** [comment]
Can you confirm that the fix works well on the branch `development`?
