### ISSUE TITLE
Implement the GUI

### ISSUE THREAD

**Issue by soywod** [soywod/himalaya#343]

**Comment by paulrouget** [comment]
I see that there's already a PR for that.

I have myself been experimenting a bit with himalaya as a backend for a slim and simple multiplatform client. It works on linux/mac and windows. I use [egui](https://crates.io/crates/egui).

It's functional, but I'm obviously reaching the limits of what Himalaya can do (no local db/cache), so it's a bit slow, and the imap emails are not being updated (Himalaya only notify on new emails). That's just a simple prototype (no way to send emails yet), but if there's any interest for this approach, I'd be happy to cleanup my code and submit a PR. I think it would fit nicely as it would only add one dependency to the project (egui).

<img width="941" alt="Screenshot 2022-09-15 at 16 29 53" src="https://user-images.githubusercontent.com/373579/190356425-39d70961-a357-4193-94aa-816007f8b462.png">

**Comment by soywod** [comment]
> I see that there's already a PR for that.

Indeed but it is not so active. Other PRs are welcomed :slightly_smiling_face: 

> It's functional, but I'm obviously reaching the limits of what Himalaya can do (no local db/cache), so it's a bit slow, and the imap emails are not being updated (Himalaya only notify on new emails). That's just a simple prototype (no way to send emails yet), but if there's any interest for this approach, I'd be happy to cleanup my code and submit a PR. I think it would fit nicely as it would only add one dependency to the project (egui).

I heard about `egui` but I never used it, the result looks really promising!! I love it. It could be so great to have such a cross-platform GUI!

I also use Himalaya as my main email client (with the [emacs plugin](https://github.com/dantecatalfamo/himalaya-emacs)) and I cannot agree more about the slowness of the IMAP backend. This should be improved by https://github.com/soywod/himalaya/issues/342 (I already have a working prototype, I just need time to test and release it).

For now Himalaya is just a CLI. But I'm working on extracting a fully functional Rust library containing all the email management logic: this way the CLI becomes a simple client. I almost finished, I'm in the cleaning phase. Once the CLI and the lib are stable enough, I will close this GitHub repo (everything moves to [sourcehut](https://git.sr.ht/~soywod/) https://github.com/soywod/himalaya/discussions/399). Starting from this point, implementing the GUI could be done easily!

Regarding your contribution, I can propose you two things. Thanks to the lib, the GUI can be written in a separated repository:

- You can create the repository, which means you accept the fact to be the maintainer of the Himalaya's GUI, is it something you are interested in?
- I can create the repository, you send your PR, which means I engage myself to learn about `egui` and to maintain the repository. I have time [and money](https://nlnet.nl/project/Himalaya/) to support this, so it is not a problem for me.

We can also be both maintainers, but it requires us to discuss more. I don't know to which degree you would like to be involved in the project?

**Comment by paulrouget** [comment]
I'm excited to play with the new server/cache system!

Let me make some progress on the `egui` port and put together a proper repo. I'm interested to see how this will play out. Then I'll see if I want to maintain Himalaya's gui (I do have time in the coming month to work on such a project).

Should I migrate my code base to https://git.sr.ht/~soywod/himalaya-lib already? Or should I wait?

**Comment by soywod** [comment]
> Should I migrate my code base to https://git.sr.ht/~soywod/himalaya-lib already? Or should I wait?

I need first to publish the stable version on [crates.io](https://crates.io/crates/himalaya-lib), I let you know when it is ready!

**Comment by soywod** [comment]
Be aware that the only documentation you will find is the `crates.io` one and the `himalaya-cli` (which is the first client consuming the lib, it will be a good starting point for the GUI).

**Comment by paulrouget** [comment]
Awesome! I made good progress on my side. Will migrate to the library soon.

**Comment by paulrouget** [comment]
<img width="862" alt="Screenshot 2022-09-23 at 09 21 11" src="https://user-images.githubusercontent.com/373579/191876848-7d6b1053-3872-4664-acbc-27520d48de24.png">

**Comment by soywod** [comment]
Looks soooo great, cannot wait to see how it will integrate with the lib! The CLI is not yet released but you can have a usage example on the [`develop`](https://github.com/soywod/himalaya/tree/develop) branch.

**Comment by paulrouget** [comment]
I got the very basics working (folder listing, mail listing, mail reading) with the lib. I just wish `himalaya::config::DeserializedConfig` was part of the lib. I understand that's more of a frontend logic though.

**Comment by soywod** [comment]
> I got the very basics working (folder listing, mail listing, mail reading) with the lib.

Awesome, please feel free to give your feedback so I can improve the lib.

> I just wish `himalaya::config::DeserializedConfig` was part of the lib.

Initially it was the case, but then I realized this struct is too linked to the CLI (clients can store config the way they want: JSON, TOML, database etc). Although the CLI is available on crates.io, so you could import the struct from the `himalaya` crate.

**Comment by paulrouget** [comment]
> Although the CLI is available on crates.io, so you could import the struct from the himalaya crate.

That's what I ended doing.

> please feel free to give your feedback so I can improve the lib.

I will. At the moment, I am focusing on the putting together a proper UI tookit and I'm still experimenting with different approaches and frameworks. The Himalaya integration for now is very basic and I haven't look deeply into the lib.

My goal for now is to have a good-enough UI toolkit (perf/customisation/integration with OS), be UI backend agnostic (don't want to rewrite all the things if I ended up ditching egui), and have a modular-enough UI component system (don't want this to look like a big blob of buttons fighting around).

Just one thing about the lib:

As for now, the Himalaya integration is just a thread sending messages to the UI loop, listing folders, envelopes, and mail bodies. It's pulled at startup. Nothing live. Is there already a system in place to get notify/watch to work with Rust callbacks instead of commands?

**Comment by soywod** [comment]
> My goal for now is to have a good-enough UI toolkit (perf/customisation/integration with OS), be UI backend agnostic (don't want to rewrite all the things if I ended up ditching egui), and have a modular-enough UI component system (don't want this to look like a big blob of buttons fighting around).

It is exactly the aim I try to achieve with Himalaya!

> Is there already a system in place to get notify/watch to work with Rust callbacks instead of commands?

Not at the moment. I just "extracted" the logic not so long time ago, I do not know yet where to go. Like you, my aim is to plug everything together so the CLI works like before. Then we will be able to make it grow properly.

**Comment by soywod** [comment]
I gather all Himalaya issues to the same [bug tracker](https://todo.sr.ht/~soywod/himalaya), so I transfer the issue [here](https://todo.sr.ht/~soywod/himalaya/13).
