### ISSUE TITLE
himalaya vim: "cannot find notmuch message from short hash"

### ISSUE THREAD

**Issue by jghauser** [soywod/himalaya#354]
For most messages, when I try to open them in the Himalaya vim frontend, I get the following type of error:
```
Error: cannot find notmuch message from short hash "0"                                                    
Caused by:                                                                                                
    0: cannot find maildir message id from short hash "0"                                                 
    1: the short hash "0" matches more than one hash: 0eccf39fd69720c93f816ac00b396467, 038608455a46c531a0
3ac4adc69f7695     
```
Sometimes the short hash number is different, though mostly it's a '0'.

**Comment by soywod** [comment]
This means that "0" is not specific enough, Himalaya finds more that one
message starting by "0". Try with "0e" or "03"? When you list messages
you see only "0" in the hash column?

On 05 Apr 2022, at 13:04 (+0200), soywod/himalaya wrote:
> For most messages, when I try to open them in the Himalaya vim frontend, I get the following type of error:
> ```
> Error: cannot find notmuch message from short hash "0"  
> Caused by:  
>  0: cannot find maildir message id from short hash "0"  
>  1: the short hash "0" matches more than one hash: 0eccf39fd69720c93f816ac00b396467, 038608455a46c531a0
> 3ac4adc69f7695  
> ```
> Sometimes the short hash number is different, though mostly it's a '0'.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/soywod/himalaya/issues/354
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>

-- 
Cordialement
Clément DOUIN
Développeur Web Full-Stack
https://soywod.me

**Comment by jghauser** [comment]
What I do is (after `:Himalaya`) is press enter to select a message. I'm not setting the hash myself. And the hash in the column isn't '0', it's for example 'd6f'. It's always three characters.

**Comment by soywod** [comment]
Ow I see. I think the Vim regex used to grab the id is broken with
maildir/notmuch backends. I will fix this for the next release!

On 05 Apr 2022, at 15:21 (+0200), soywod/himalaya wrote:
> What I do is (after `:Himalaya`) is press enter to select a message. I'm not setting the hash myself. And the hash in the column isn't '0', it's for example 'd6f'. It's always three characters.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/soywod/himalaya/issues/354#issuecomment-1088696653
> You are receiving this because you commented.
> 
> Message ID: ***@***.***>

-- 
Cordialement
Clément DOUIN
Développeur Web Full-Stack
https://soywod.me

**Comment by jghauser** [comment]
Great, thanks a lot! :)

**Comment by skbolton** [comment]
All the examples in the wikis show the ids being sequences of numbers so the regex match woks. But with maildir folders the short IDs can contain letters. I think that's the issue as I am affected by this as well and that's my situation.

**Comment by soywod** [comment]
https://github.com/soywod/himalaya/pull/383 fixes the issue, it should be shipped with the next release!
