### ISSUE TITLE
[Question] Why wrapping the backends in Boxes?

### ISSUE THREAD

**Issue by TornaxO7** [soywod/himalaya#359]
Hi! I've got a little question about the code. Why do you need the [`Box::new`](https://github.com/soywod/himalaya/blob/development/cli/src/main.rs#L78) for the [`backend`](https://github.com/soywod/himalaya/blob/development/cli/src/main.rs#L74) variable? Can't we just write

```rust
let backend: Box<&mut dyn Backend> = match backend_config {
    #[cfg(feature = "imap-backend")]
    BackendConfig::Imap(ref imap_config) => ImapBackend::new(&account_config, imap_config),
    // and so on
}
```
?

**Comment by soywod** [comment]
> Hi! I've got a little question about the code. Why do you need the
> `Box::new` for the `backend` variable?

If I remember well, the rust compiler was not so happy about passing a
`&mut dyn Backend` directly. But I may have mistaken sth, I will give
another try. Thanks for pointing it out!

**Comment by soywod** [comment]
It looks like I cannot remove the `Box`, otherwise the compiler complains about `the trait "Sized" is not implemented for "dyn Backend"` :disappointed:
