### ISSUE TITLE
fix: reset ansi after terminal command

### ISSUE THREAD

**Issue by zanona** [soywod/himalaya#364]
Hi, thank you so much for himalaya. It's such a great tool and so easy to set-up. I was delaying configuring mutt for years but fortunately after finding himalaya that's no longer necessary. :smiley: 

I have been running into an issue where the colour persists after a command? Perhaps it could be reset once the command finishes?

```
$ himalaya --version
himalaya 0.5.10
```

![screenshot](https://user-images.githubusercontent.com/32017/163563456-9b11f062-c71c-4fc8-ba69-f07ef1096fc4.png)

**Comment by soywod** [comment]
I think this has been fixed by #372, feel free to reopen if it does not work as expected!

**Comment by soywod** [comment]
> I have been running into an issue where the colour persists after a
> command? Perhaps it could be reset once the command finishes?

I also noticed last time, nice catch :D

As you said, it must miss a reset command somewhere. Thank you for
pointing it out!
