### ISSUE TITLE
Refactor draft management

### ISSUE THREAD

**Issue by TornaxO7** [soywod/himalaya#365]
As discussed in the [discussion](https://github.com/soywod/himalaya/discussions/345#discussioncomment-2522132) it's probably better to store the drafts somewhere else than in `/tmp`.

**Comment by soywod** [comment]
I gather all Himalaya issues to the same [bug tracker](https://todo.sr.ht/~soywod/himalaya), so I transfer your issue [here](https://todo.sr.ht/~soywod/himalaya/11).
