### ISSUE TITLE
Gmail and Less Secure Apps

### ISSUE THREAD

**Issue by phdavis1027** [soywod/himalaya#368]
On May 30th, Gmail will remove support for apps not supporting OAuth 2.0. Turning off less secure apps was the only way I could use Himalaya for my gmail account. Is there a plan to support Gmail after this change?

**Comment by zanona** [comment]
:thinking:  I access my account on Himalaya with App passwords and I cannot see any discontinuation notice over there?
https://myaccount.google.com/apppasswords

**Comment by phdavis1027** [comment]
Interesting, that link leads me to Google telling me "The setting you are looking for is not available for your account."

**Comment by phdavis1027** [comment]
Looks like it's a 2-step verification issue. Thanks and sorry for the confusion!

**Comment by zanona** [comment]
No worries :)
Hopefully this will work out for you. If it does, don't forget to close the issue :+1:

**Comment by anthr76** [comment]
Is there any timeline or thought into using oauth? I'd like to incorporate office 365 but without oauth that won't be possible.

**Comment by soywod** [comment]
> Looks like it's a 2-step verification issue. Thanks and sorry for the confusion!

Let us now if it fixed your issue!

> Is there any timeline or thought into using oauth? I'd like to incorporate office 365 but without oauth that won't be possible.

This is a different issue, I invite you to open a dedicated issue for this feature :wink:
