### ISSUE TITLE
Add option to disable color output

### ISSUE THREAD

**Issue by pleshevskiy** [soywod/himalaya#371]
At the moment, the functionality of himalaya does not really suit me and I am writing some scripts for experimentation. However, in the scripts I have to clear the colors in order for himalaya to get the correct input data. It would be great to add an option that removes colors from the result

**Comment by pleshevskiy** [comment]
https://github.com/BurntSushi/termcolor#automatic-color-selection

Solved my problem

`NO_COLOR=1 himalaya list`

**Comment by soywod** [comment]
Yes indeed, there is a section about it in the wiki https://github.com/soywod/himalaya/wiki/Tips:disable-colors.
