### ISSUE TITLE
Config QQ Mail or Foxmail

### ISSUE THREAD

**Issue by luckyymme** [soywod/himalaya#376]
How can I config QQ Mail or Foxmail?

**Comment by luckyymme** [comment]
When I set Name to 'qmail', It works. But It cannot connect IMAP Server.

**Comment by luckyymme** [comment]
When I touch a file like $HOME/.himalayrc, but It cannot find this. $HOME/.config/himalay/config.toml can be found.

**Comment by luckyymme** [comment]
My user is root user.

**Comment by soywod** [comment]
I invite you to read the [wiki](https://github.com/soywod/himalaya/wiki/Configuration:config-file), you have everything you need to set up your accounts. If you still have issues then you can open a [discussion](https://github.com/soywod/himalaya/discussions) or another issue.
