### ISSUE TITLE
Cyrillic folder names aren't parsed in Cyrillic

### ISSUE THREAD

**Issue by acid-bong** [soywod/himalaya#381]
I have a mail.ru address, which is a Russian-speaking service, and its folders have Russian names.

This is how they look normally (aerc):
![изображение](https://user-images.githubusercontent.com/94849097/168460752-4de37191-9e01-4ad4-89a9-6536ed87c040.png)

This is how himalaya outputs them:
![изображение](https://user-images.githubusercontent.com/94849097/168460733-8257b439-b88e-4d32-9f71-c4a5eb3a690a.png)
(Sent and Trash were autocreated by other clients, default folders have Russian names)

For comparison, Cyrillic in letters is shown normally:
![изображение](https://user-images.githubusercontent.com/94849097/168460818-978e2570-ecc0-4e77-aca8-5821ad9bdbcb.png)

**Comment by acid-bong** [comment]
For more context, if needed: OS is Artix Linux, Himalaya is packaged by Arch, latest version at the moment

**Comment by soywod** [comment]
Interesting issue, it looks like mailbox names are not parsed correctly. It is strange because I remember having tested with one of my french account and special chars like `é` were displaying properly. Thanks for pointing it out!

**Comment by pleshevskiy** [comment]
I described this problem here #370

**Comment by soywod** [comment]
@pleshevskiy is right, this issue is the same as described in his issue. I close this one for duplicate then. @acid-bong I invite you to follow #370 instead. Thank you!
