### ISSUE TITLE
[Feature Request] Create kanban-board

### ISSUE THREAD

**Issue by TornaxO7** [soywod/himalaya#387]
It would be nice in my opinion to haev a kanban-board to see what is currently done by whom and which what is still possible to do.

**Comment by soywod** [comment]
Here a first draft: https://github.com/users/soywod/projects/1/views/6. I put 3 columns: 1 overview (kanban style), 1 for tasks to define (they need more thinking before acting) and 1 for tasks to do (they are well defined, they just need to be done).

**Comment by TornaxO7** [comment]
Eh, is that normal that I can adjust the kanban-board as well?

**Comment by soywod** [comment]
Yes because I added you as writer, so you can assign tasks yourself if you want :)

**Comment by soywod** [comment]
They are also ordered by priority

**Comment by TornaxO7** [comment]
> Yes because I added you as writer, so you can assign tasks yourself if you want :)

Oh! Thank you! c(^-^)c
