### ISSUE TITLE
Not receiving a notification

### ISSUE THREAD

**Issue by davidhaley** [soywod/himalaya#394]
![out](https://user-images.githubusercontent.com/11729897/172732673-e89d50e2-0579-468d-a048-31a7c3d1ccc1.png)

I set up a systemd service to run `himalaya notify`; however, I don't receive a notification (even though the logs mention that it is running the command). If I run `/usr/bin/notify-send subject body` I receive a notification.

Here is the service:

```
[Unit]
Description=Himalaya Notify

[Service]
Type=simple
ExecStart=/home/dhw/wkspaces/personal/dev_config_ubuntu/start_himalaya_notify.sh
ProtectHome=off
Environment="HOME=/home/dhw"

[Install]
WantedBy=multi-user.target
```
And the script that it runs:

```
#!/bin/bash

RUST_LOG=trace /home/dhw/.local/bin/himalaya notify
```

Thank you.

**Comment by soywod** [comment]
Could you try with a more minimalist config (see https://github.com/soywod/himalaya/wiki/Usage:msg:notify) to see if it works for you? Try also to set directly the `himalaya notify` inside the systemd service to see. Let me know!

**Comment by davidhaley** [comment]
Thank you for your help!

I receive a notification if I run `himalaya notify` directly in the terminal and send myself an email.

However, I used the example service and stored it in the example location, set the executable bit, and I receive a `(code=exited, status=203/EXEC)` from systemd upon starting the service.

![image](https://user-images.githubusercontent.com/11729897/172958937-c8eda973-0fbd-45f0-8477-6b9e5db40013.png)
![image](https://user-images.githubusercontent.com/11729897/172958970-5c9a8191-794a-4f44-9e6d-dfa32c4f9614.png)

This isn't related to himalaya, so we can close this issue if you want. I will tinker and try to figure it out (I can post the solution here once I've found it).

Cheers!

**Comment by davidhaley** [comment]
Figured it out, I needed to add the full path to the executable.

```
[Unit]
Description=Himalaya new messages notifier

[Service]
ExecStart=**/home/dhw/.local/bin/**himalaya notify
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

It's working now. Thank you!

**Comment by soywod** [comment]
Awesome, glad to hear you made it work! Feel free to edit the wiki if you find it pertinent (for eg adding an absolute path to himalaya) to prevent future users  deeling with the same issue!
