### ISSUE TITLE
Add autocompletion to CLI

### ISSUE THREAD

**Issue by thomasaarholt** [soywod/himalaya#395]
It would be nice if I could type `himalaya l<tab>` to autocomplete into `list`. At the moment I get a list of all the files in the current directory. On zsh on macos 12.3.1

**Comment by soywod** [comment]
Did you generate your completion file as described in the [wiki](https://github.com/soywod/himalaya/wiki/Configuration:completion)?

**Comment by thomasaarholt** [comment]
Apologies, I didn’t see that. I did a Google search for “himalaya completion email” but didn’t find anything. Thanks for linking!
