### ISSUE TITLE
OAuth 2.0 support

### ISSUE THREAD

**Issue by vlashada** [soywod/himalaya#398]
Are there any plans to support OAuth 2.0? That would help adding gmail support

**Comment by soywod** [comment]
There is no concrete plan for this feature, let's keep this issue as a reminder. But OAuth is not required for adding gmail account, isn't it? Check https://github.com/soywod/himalaya/issues/368 and https://github.com/soywod/himalaya/wiki/Troubleshooting:gmail-credentials.

**Comment by vlashada** [comment]
No, it is not, but using OAuth 2.0 is really nice, especially if you already have oauth setup on your machine

**Comment by mborejdo** [comment]
Would also be great to be able to use oauth with o365 as basic-auth support is being deprecated

**Comment by AndrewWinterman** [comment]
Oauth is needed for enterpries accounts as far as i can tell

**Comment by soywod** [comment]
I gather all Himalaya issues to the same [bug tracker](https://todo.sr.ht/~soywod/himalaya), so I transfer your issue [here](https://todo.sr.ht/~soywod/himalaya/9).
