### ISSUE TITLE
Unlock OpenPGP Secret Keys

### ISSUE THREAD

**Issue by irondeau** [soywod/himalaya#411]
Using the `pass` utility in the `passwd-cmd` settings where the OpenPGP key is password-protected causes himalaya to throw the error

```
Error: cannot login to IMAP server

Caused by:
    No Response: [UNAVAILABLE] Temporary authentication failure. [2022-09-08 06:10:31]
```

This error can be mitigated by first running a command such as `pass show email/mail@example.com` and entering the passphrase in the prompt shown.

```
┌───────────────────────────────────────────────────────────────┐
│ Please enter the passphrase to unlock the OpenPGP secret key: │
│ "John Doe <mail@example.com>"                                 │
│ 4096-bit RSA key, ID ################,                        │
│ created 2022-09-07 (main key ID ################).            │
│                                                               │
│                                                               │
│ Passphrase: _________________________________________________ │
│                                                               │
│         <OK>                                   <Cancel>       │
└───────────────────────────────────────────────────────────────┘
```

After this passphrase has been entered, the gpg utility will not ask again for the passphrase for a brief time. Is there a way to allow himalaya to display this prompt when the user has not yet been challenged?

Note, this behavior also happens in vim, where without first entering the `pass show` command, himalaya will result in failure.

**Comment by soywod** [comment]
Let me know if one of those issues helps you:

- https://github.com/soywod/himalaya/issues/377
- https://github.com/soywod/himalaya/issues/350

**Comment by irondeau** [comment]
> Let me know if one of those issues helps you:
> 
> * [Pinentry #377](https://github.com/soywod/himalaya/issues/377)

Yes, this issue helped solve my problem. I skipped past this one because the title seemed irrelevant to the problem I was encountering. Thanks for your help.
