### ISSUE TITLE
Custom Color Configuration

### ISSUE THREAD

**Issue by irondeau** [soywod/himalaya#412]
I'm having troubles properly coloring certain portions of the himalaya output, particularly the borders and underlines. Here are my terminal colors:

![neofetch](https://user-images.githubusercontent.com/25674784/189167527-adaa8e67-8435-4073-af33-791061adf541.png)

The email info borders seem to be using the same color as the terminal background, so they appear to be hidden.

![himalaya](https://user-images.githubusercontent.com/25674784/189167526-173c7bff-94d6-420a-9ff2-d2db4e5a24ad.png)

A similar problem occurs in nvim where the border background is inverted. This may be a problem with my nvim theme admittedly; however, I don't believe my theme is configured to change the background color of the vertical line character. Additionally, there is no underline under column headers except for the DATE column.

![himalaya-vim](https://user-images.githubusercontent.com/25674784/189167523-0c251aef-6022-47a8-8679-1f259ad3e574.png)

I did not find any instructions on how to configure terminal colors in the configuration wiki (other than disabling them entirely). It would be preferable to be able to override certain colors since not all color pallettes contrast in a similar manner.

**Comment by soywod** [comment]
There is 2 different problems:

1. Regarding the CLI, it could be able to customize the colors. We can keep the issue open for this purpose.
2. Regarding the Vim plugin, there is no documentation about managing colors (yet) but it should be doable. Have a look at https://git.sr.ht/~soywod/himalaya-vim/tree/master/item/syntax/himalaya-email-listing.vim, you will see the list of available highlight names from Himalaya. For example, to override the separator, you could add to your config `highlight HimalayaSeparator cterm=NONE ctermbg=17 gui=NONE guibg=#00005f`

**Comment by soywod** [comment]
I gather all Himalaya issues to the same [bug tracker](https://todo.sr.ht/~soywod/himalaya), so I transfer your issue [here](https://todo.sr.ht/~soywod/himalaya/7).
