### ISSUE TITLE
segfault on Alpine

### ISSUE THREAD

**Issue by fancycade** [soywod/himalaya#418]
I've built version 0.6.1 from source on latest Alpine Linux. Build was successful and some commands worked. However, I get segfault on `himalaya list`. 

cargo version = 1.64.0

It has been a little bit since I've messed around with himalaya so I'm not sure if previous versions worked.

Happy to try anything out to help fixing this.

**Comment by soywod** [comment]
Could you share your config and the logs of `RUST_LOG=debug himalaya list`?

**Comment by fancycade** [comment]
Config:
```
display-name = "Harley Swick"
downloads-dir = "~/Downloads"
signature = "Best Regards,"

[migadu]
default = true
email = "fc@mailcat.space"

backend = "imap" # imap, maildir or notmuch
imap-host = "imap.migadu.com"
imap-port = 993
imap-login = "fc@mailcat.space"
imap-passwd-cmd = "echo 'secretpassword'"

sender = "smtp" # smtp or sendmail
smtp-host = "smtp.migadu.com"
smtp-port = 465
smtp-login = "fc@mailcat.space"
smtp-passwd-cmd = "echo 'secretpassword'"
```

Logs:
```
[2022-10-16T18:58:36Z INFO  himalaya::compl::args] entering completion command matcher
[2022-10-16T18:58:36Z DEBUG himalaya::config::config] path: None
[2022-10-16T18:58:36Z INFO  himalaya::domain::imap::args] entering imap command matcher
[2022-10-16T18:58:36Z DEBUG himalaya::domain::email::args] list command matched
[2022-10-16T18:58:36Z DEBUG himalaya::domain::email::handlers] page size: 10
[2022-10-16T18:58:36Z DEBUG himalaya_lib::backend::imap::backend] create TLS builder
[2022-10-16T18:58:36Z DEBUG himalaya_lib::backend::imap::backend] insecure: false
Segmentation fault
```

**Comment by fancycade** [comment]
Not much of a surprise but it looks the error is coming from TlsConnector::builder in native_tls.

I'll mess with native_tls to try to figure out the issue and report the bug there.

**Comment by soywod** [comment]
Thank you @fancycade :pray:

**Comment by fancycade** [comment]
Fortunately this is a known issue with a work around.

```
RUSTFLAGS=-Ctarget-feature=-crt-static cargo build --release
```

Fixes the problem.

sfacklet/rust-native-tls#190

**Comment by soywod** [comment]
I guess we can close this issue since it is not related to Himalaya (plus there is workarounds). Maybe we could add an entry in the wiki?
