### ISSUE TITLE
About tags/flag and backend ? 

### ISSUE THREAD

**Issue by reyman** [soywod/himalaya#424]
Hi,

I search in the doc and i didn't found the info about how tags/flag  worked with associated backend.

With : 
- notmuch, tag/flag are linked to notmuch tags? 
- maildir (mu) ?
- imap ?
I suppose the behavior are different ? 

I found your project very interesting, i'm using Guix linux system (a nix like system) + doom-emacs, i think packaging himalaya to it could be cool. I look at it when i have free time.

Best

**Comment by soywod** [comment]
> I search in the doc and i didn't found the info about how tags/flag worked with associated backend.

It is true that it is a bit messy. To summarise:

* Notmuch: flags are linked to notmuch tags
* Malidir: flags correspond to maildir flags (see https://doc.dovecot.org/admin_manual/mailbox_formats/maildir/#maildir-filename-extensions)
* IMAP: flags match regular IMAP flags (default and custom ones)

I have an open issue about developing a common interface (compatible across all backends) for the query system and the flags, but it is not a priority for now.

> I found your project very interesting, i'm using Guix linux system (a nix like system) + doom-emacs, i think packaging himalaya to it could be cool.

I do not know Guix, but sure it could be great! About the [Emacs plugin](https://github.com/dantecatalfamo/himalaya-emacs), it is already accessible from the [MELPA](https://melpa.org/#/himalaya) repository :slightly_smiling_face:

**Comment by soywod** [comment]
I gather all Himalaya issues to the same [bug tracker](https://todo.sr.ht/~soywod/himalaya), so I transfer your issue [here](https://todo.sr.ht/~soywod/himalaya/5).
