### ISSUE TITLE
Difference between Notify and Watch

### ISSUE THREAD

**Issue by FluffyDiscord** [soywod/himalaya#425]
Is there any difference? The wiki pages looks the same.

**Comment by soywod** [comment]
Those 2 commands are kind of legacy, it is a bit messy. To summarise:

* `notify` triggers a command every time a new email arrives in a mailbox (using the IMAP [IDLE](https://datatracker.ietf.org/doc/html/rfc2177) mode)
* `watch` triggers all commands every time a change occurs on a mailbox (using the IMAP IDLE mode also)

So you can see the `notify` command as a helper for the `watch` command. This last one is more generic.

**Comment by soywod** [comment]
The wiki is not so up to date for those commands, I will fix this!

**Comment by FluffyDiscord** [comment]
Thanks for the explanation ❤️

**Comment by soywod** [comment]
I just updated the [wiki](https://github.com/soywod/himalaya/wiki/Usage:real-time-notifications), I hope it is clearer now. Thank you for having pointed it out!
