### ISSUE TITLE
Message UID for Notify/Watch

### ISSUE THREAD

**Issue by FluffyDiscord** [soywod/himalaya#426]
Can we have another placeholder for message ID ? eg. `<uid>`

**Comment by soywod** [comment]
You mean to watch changes only on a particular email? I think it is doable for the watch command, but it does not make sense for the notify command (since this last one trigger commands when new emails arrive).

**Comment by FluffyDiscord** [comment]
> You mean to watch changes only on a particular email? I think it is doable for the watch command, but it does not make sense for the notify command (since this last one trigger commands when new emails arrive).

No, I mean something different.

I think the best would be to add to the wiki which fields are available in the notify-cmd.

The example shows `notify-send "📫 <sender>" "<subject>"`. Do we only have these two fields or more?

**Comment by soywod** [comment]
> I think the best would be to add to the wiki which fields are available in the notify-cmd.

Oh I see. I did not think about adding dynamic parameters (I put `<sender>` and `<subject>` just for the example), it is a good idea. We can start with `<sender>`, `<subject>` and `<id>` and see how it behaves. I have other priorities right now, let's keep this issue open for later. Thank you!

**Comment by soywod** [comment]
I gather all Himalaya issues to the same [bug tracker](https://todo.sr.ht/~soywod/himalaya), so I transfer your issue [here](https://todo.sr.ht/~soywod/himalaya/4).
