### ISSUE TITLE
BUG: address parser -> validity

### ISSUE THREAD

**Issue by salkin-mada** [soywod/himalaya#428]
~ 
❯ himalaya -a bureaukrati read 36
Error: cannot parse From value: Oslo kommune, Bymiljøetaten <ikke_svar@varsling24.no>

Caused by:
    Invalid address found: must contain a '@' symbol

**Comment by soywod** [comment]
Duplicate https://github.com/soywod/himalaya/issues/402, the address is not well formatted according to the RFC (and this happens a lot), I need to think well about how to deal with such cases.
