### ISSUE TITLE
With "sort" command, "-s" returns off-by-one shortened list

### ISSUE THREAD

**Issue by fauxmight** [soywod/himalaya#435]
With the `search` or `list` command, `-s` returns the expected number of envelopes.

With the `sort` command, the returned set of envelopes is one fewer than requested by `-s`

**Comment by soywod** [comment]
I confirm the bug. The pagination is not handled well for the `sort` command. Thank you!

---

Himalaya is slowly migrating away from GitHub. The new bug tracker is now on [sourcehut](https://sr.ht/). I move your issue [here [#30]](https://todo.sr.ht/~soywod/himalaya/30). You can subscribe to the thread by sending an email at [~soywod/himalaya/30/**subscribe**@todo.sr.ht](mailto:~soywod/himalaya/30/subscribe@todo.sr.ht) (and unsubscribe to it by sending an email at [~soywod/himalaya/30/**unsubscribe**@todo.sr.ht](mailto:~soywod/himalaya/30/unsubscribe@todo.sr.ht)).
