### ISSUE TITLE
With "sort" command, "--page-size" argument is not expected/accepted

### ISSUE THREAD

**Issue by fauxmight** [soywod/himalaya#436]
When using the sort command if one provides a `--page-size` argument, himalaya returns the following error:

`
error: Found argument '--page-size' which wasn't expected, or isn't valid in this context
        Did you mean --page?
`

Passing the short version (`-s`) works as expected.

**Comment by soywod** [comment]
The page size argument has been renamed from `--size` to `--page-size` on `develop` (the wiki actually reflects the state on `develop`, this behaviour will change in the future). Which explains why the short `-s` works for you but not the long.
