### ISSUE TITLE
QUERY *must* be the first argument to "sort" command

### ISSUE THREAD

**Issue by fauxmight** [soywod/himalaya#437]
When using the `sort` command, one cannot pass arguments as noted in the wiki documentation:

`himalaya sort -c arrival -c from not seen`

returns

```
error: The following required arguments were not provided:
    <QUERY>...
```

If the QUERY argument is passed FIRST, the sort command works as expected. It is not clear whether this is intended behavior and the documentation requires updating or this is a bug.

**Comment by soywod** [comment]
This bug has been fixed on `develop` (not yet available) and will be available for the next release [v0.6.2](https://github.com/soywod/himalaya/pull/433).
