### ISSUE TITLE
"--color" or "-C" option does not work

### ISSUE THREAD

**Issue by fauxmight** [soywod/himalaya#438]
Use of the `-C` or `--color` option yields
`error: Found argument '-C' which wasn't expected, or isn't valid in this context`
or
`error: Found argument '--color' which wasn't expected, or isn't valid in this context`

**Comment by soywod** [comment]
Could you share your command? I suspect you misplaced the argument, this one is a global one and should be placed before any command. `himalaya -C list` is correct but not `himalaya list -C`.

**Comment by soywod** [comment]
I can confirm that you misplaced the argument, `himalaya -C never list` works as expected on `develop`.
