### ISSUE TITLE
Older SSL/TLS versions

### ISSUE THREAD

**Issue by jubalh** [soywod/himalaya#440]
Is there a way to configure himalaya to connect even to servers that use outdated ssl versions?

```
himalaya
Error: cannot connect to imap server

Caused by:
    error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
```

**Comment by soywod** [comment]
> Is there a way to configure himalaya to connect even to servers that
> use outdated ssl versions?

No, there is no way to configure such thing. Do you know which SSL
version your server uses?

**Comment by soywod** [comment]
Strange because TLS 1.0 seems to be supported by `native-tls`: https://github.com/sfackler/rust-native-tls/blob/774a19cecb694dc6e414c2ada9bd5f768a0b9b75/src/imp/openssl.rs#L32. Could you share your Himalaya config?

**Comment by jubalh** [comment]
> Could you share your Himalaya config?

Quite basic, and I removed the (private) domain name:
```
display-name = "Test"
downloads-dir = "~/test/downloads"

[myserver]
default = true
email = "user@myserver.org"

backend = "imap"
imap-host = "imap.myserver.org"
imap-port = 143
imap-login = "user@myserver.org"
imap-passwd-cmd = "pass user@myserver.org"

sender = "smtp"
smtp-host = "smtp.myserver.org"
smtp-port = 25
smtp-login = "user@myserver.org"
smtp-passwd-cmd = "pass user@myserver.org"
```

**Comment by jubalh** [comment]
Is there anything I can do to further debug this?

**Comment by soywod** [comment]
> Is there anything I can do to further debug this?

Did you try to use the port 993 instead of 143? Or to use STARTTLS with
the option `imap-starttls = true`?

**Comment by jubalh** [comment]
I tried that and started himalaya. Now it hangs since several minutes. It can't be downloading since it didn't get my password via pass yet. And I assume there would also be a connection timeout.

**Comment by soywod** [comment]
> I tried that and started himalaya. Now it hangs since several minutes.

So something is wrong with the config. I am a bit out of idea :/ is
there any way for me to have an access so I can try to debug also?

**Comment by jubalh** [comment]
I will close this for now since I didn't find the time to further investigate.
I hope it's okay if I comment later again.

**Comment by soywod** [comment]
Yes sure! Just for information: the bug trackers moves away from GitHub, you need now to send an email at `soywod/pimalaya@todo.sr.ht`, see https://github.com/soywod/himalaya/blob/master/CONTRIBUTING.md#contributing.
