### ISSUE TITLE
Date is UTC not localtime

### ISSUE THREAD

**Issue by geri1701** [soywod/himalaya#441]
The time in the Date column is displayed in UTC (without offset), I would expect local time here. Is that on purpose?

**Comment by soywod** [comment]
> The time in the Date column is displayed in UTC (without offset), I
> would expect local time here. Is that on purpose?

If I remember well it is a naive local time (without timezone offset)
and not UTC. Anyway on the `develop` branch it is not the case
anymore. Starting from the next release it will show a RFC3339 string
which contains the timezone (looking like
"2023-02-04T11:07:39+01:00"). So we can close this issue :)

**Comment by geri1701** [comment]
Thank you! :)
