### ISSUE TITLE
QQ email Error: cannot get imap password: password is empty

### ISSUE THREAD

**Issue by newyorkthink** [soywod/himalaya#445]
imap-passwd-cmd = "is my pwd"

I seted it , but it not work

**Comment by soywod** [comment]
As described in the [doc](https://pimalaya.org/himalaya/docs/cli/configuration/account/backend/imap.html), `imap-passwd-cmd` takes a shell command that retrieves your password. You cannot put directly your password for obvious security reasons. Also, as mentioned in the [README](https://github.com/soywod/himalaya#contributing) and in the issue template, do not use GitHub issues. Instead, send an email at [~soywod/pimalaya@todo.sr.ht](mailto:~soywod/pimalaya@todo.sr.ht).
