### ISSUE TITLE
support ip-addresses as imap/smtp host

### ISSUE THREAD

**Issue by hitchhooker** [soywod/himalaya#448]
11038 🕸 cat config.toml                                                                                                                                                   [~]
[email-reading-format]
type = "auto"

["tommi@example.lol"]
backend = "imap"
email = "tommi@example.lol"
default = true
display-name = "Tommi"
sender = "smtp"
smtp-host = "127.0.0.1"
smtp-port = 1025
smtp-starttls = true
smtp-login = "tommi@example.lol"
smtp-passwd-cmd = "pass show protonmailbridge"
sync = false
sync-folders-strategy = "all"
imap-host = "127.0.0.1"
imap-port = 1143
imap-starttls = true
imap-login = "tommi@example.lol"
imap-passwd-cmd = "pass show protonmailbridge"

["tommi@example.lol".email-reading-format]
type = "auto"
pc02 𓅨 ~
11039 🕸 11032 🕸 himalaya                                                                                                                                                          [~]
Error: cannot login to imap server

Caused by:
    presented server name type wasn't supported

**Comment by hitchhooker** [comment]
Areplacing fields with localhost seems to work as workaround, leading to another issue related to certificates:
```
Error: cannot login to imap server

Caused by:
    invalid peer certificate contents: invalid peer certificate: CaUsedAsEndEntity
```

**Comment by soywod** [comment]
For supporting IP addresses, I opened an issue at
<https://todo.sr.ht/~soywod/pimalaya/80>.

For the CaUsedAsEndEntity error: I would advise to wait for the next
release, it may resolve this issue. I let you know.

**Comment by soywod** [comment]
Bumping `rustls` to `v0.21` gave us [IP support](https://github.com/rustls/rustls/issues/184#issuecomment-1385458603) for free. It is available on master since [3b8c5ec](https://git.sr.ht/~soywod/pimalaya/commit/3b8c5ecebc126aba1906ad0ea562b720a8a4bf85) and should be available for the next CLI release.

**Comment by soywod** [comment]
New release available: https://github.com/soywod/himalaya/releases/tag/v0.8.0

**Comment by hitchhooker** [comment]
awesome, ill give it a new try

**Comment by alexsnaps** [comment]
This is from using ProtonMail's bridge, or that's certainly is my use case and I am getting the same error, despite having [installed the CA](https://proton.me/support/apple-mail-certificate) and it does work fine in the Mail.app on MacOS... 

@hitchhooker Did you get it to work? 

I'll try on a linux too and will investigate this a little further on my end.
