### ISSUE TITLE
Stop breaking configuration compatibility please

### ISSUE THREAD

**Issue by hissssst** [soywod/himalaya#452]
I would really love to open an issue in sourcehut, but emailing program I am using is broken by an incompatible update, so I am opening it here.

# Compatibility

It happened two times already, and for the first time I assumed that it was just a mistake, but the second time defines a clear pattern caused by you not knowing why compatibility is important or what semantic versioning is. That's why I came here: to share my experience in terms of making user-friendly software and to improve `himalaya` as a program.

## Why is compatibility important?

Answer is simple: users can update software without breaking their workflow. This is just handy, users won't wake up one day without ability to read emails after minor update. Their scripts won't get broken, they won't miss any notifications about important meetings, they won't miss an email about rescheduled appointment to the doctor that they were waiting for for half a year and so and so on. And still, there are many other reasons why compatibility is important.

## When compatibility can be broken

Only when it is impossible or extremely hard to remain compatible with existing solution. Adding few fields in configuration is definitely **not the case**.

## How to break compatibility

But who am I to judge. Maybe changing few fields in toml is very very important issue which can't be solved in a compatible way. So, when you're sure about it, how does one change software in incompatible way? There are many popular and useful techniques:

### Deprecation warnings

When you release a software which aims towards incompatible changes, it is really handy to support obsolete interfaces with a deprecation warning. It will give users some time to change their configurations and environments to reflect new interfaces without breaking their existing workflow right after an update.

### Semver

It is a versioning practice where the version of software defines compatibility boundaries. It looks like `1.2.3`. And the rule of thumb is: versions `1.0.0` and `2.0.0` will most definitely be incompatible. Version `1.1.0` and `1.2.0` will be forward compatible, but might be backward incompatible. Versions `1.0.1` and `1.0.2` will likely be 100% compatible in both ways (without taking implicit behavior into account)

So, when you release a new version of software which won't be compatible with any existing configuration it is a case for **major version bump**. But I would like to note that changing few fields in the configuration is not the valid cause for incompatible update

### Configuration versioning and migrations

Some developers release scripts which just migrate old configuration formats into new ones upon first call of the program. This script usually checks the version field of the configuration, to make sure whether migration is required or not

---

## Conclusion

1. Compatibility is very important
2. Stop changing fields in program configuration, please. Configuration format is the least important part of every program.
3. If you still want to change a few fields, do it with deprecation warnings, proper version and provide a migration script.

**Comment by soywod** [comment]
I agree with everything you say, except that you forgot the 4th point of
the semver's spec <https://semver.org/#spec-item-4>:

> Major version zero (0.y.z) is for initial development. Anything MAY
> change at any time. The public API SHOULD NOT be considered stable.

As you can see, not a single library from the Pimalaya project (nor a
CLI based on those libraries like Himalaya) has a version >= 1.0.0, and
for a good reason because I consider those projects still
experimental. Hence the disclamer written on all READMEs:

> Disclaimer: the project is under active development, do not use in
> production before the v1.0.0.

I try to find the best API possible to finally release the
v1.0.0 and THEN only then apply what you said.

I am sorry about your frustration related to breaking changes, but if
despite the fact I mentionned you still plan to use it for your
production, you will have to deal with it.

**Comment by soywod** [comment]
> Major version zero (0.y.z) is for initial development. Anything MAY
> change at any time. The public API SHOULD NOT be considered stable.

If it can help you to better track breaking changes: since there is no
real major version before v1, I consider the y version "major" (I bump
it when there is breaking changes) and the z version "minor" (I bump it
when there is no breaking changes).

So 0.7.3 → 0.8.0 = expect breaking changes for sure, but 0.8.0 → 0.8.1 =
do not expect breaking changes (yet could happen).

**Comment by hissssst** [comment]
Thank you for the clarification, but, please, don't bother, I've found a way to use up-to-date emailing software without breaking my workflow couple times a year, since I am just another boring user who expects software not to get broken without any real reason to do so.

In the end of the day, it is always up to the developer whether he wants to release something and package it into every linux distribution and then break compatibility without any warning. And it is totally acceptable to distribute unstable version of software for two years and then to break compatibility for every single one of the users to just change a minus to dot and add other very important and meaningful option which could just be safely implemented as an optional field. And also, it is really common to do these things couple times a year.

I understand that with opensource projects it is totally normal not to provide any guarantees considering compatibility even after the project gets funding or a huge user base. Usually, opensource is not about quality, but more about the developer's joy, and maintaining compatibility and a quality of the software is much more boring than changing configuration format. So, I totally get it and I am really sorry for bringing this up in the first place and I am sorry that I've opened an issue on github instead of sourcehut.

I hope that a 1.0 version will be released in a few years from now, and have a nice day :)
