### ISSUE TITLE
Initial config

### ISSUE THREAD

**Issue by zoechi** [soywod/himalaya#466]
Himalaya is slowly migrating away from GitHub. The new bug tracker is
now on [sourcehut](https://sr.ht/). You can submit an issue either by:

* Sending an email at
  [~soywod/pimalaya@todo.sr.ht](mailto:~soywod/pimalaya@todo.sr.ht)
  (it is the simplest since you do not need to create any account)
* Submitting [this form](https://todo.sr.ht/~soywod/pimalaya) (you
  need a free sourcehut account)

I was about to create an issue because I get only TOML parsing errors with my initial config (copied from docs). 

Then I read at the text above that the project moved to https://sr.ht. 
I registered an account there, but I haven't found anyhting about himalaya and I have to admit I never felt more lost on a website in decades.

**Comment by prmadev** [comment]
It should be as easy as sending an email to the address mentioned: ~soywod/pimalaya@todo.sr.ht


You can see other issues here: https://todo.sr.ht/~soywod/pimalaya

All the projects under Pimalaya umbrella is handled through there. The website, unlike Github does not require you to use its own mechanism for issue tracking, just simple old mailing list. 

The code for himalaya, specifically is still hosted on github. There is a nice break down of what goes where in the website: https://pimalaya.org

**Comment by soywod** [comment]
I admit that the issue template is not up-to-date and could be improved (which I will do ASAP). But did you take time to read *at least* one of the following?

- [README.md](https://github.com/soywod/himalaya?tab=readme-ov-file#contributing)
- [CONTRIBUTING](https://github.com/soywod/himalaya/blob/master/CONTRIBUTING.md) guide
- The [website](https://pimalaya.org/)

As @prmadev said you just need to send an email, I would be happy to help you if your config file parsing errors.
