### ISSUE TITLE
Set up end-to-end encryption

### ISSUE THREAD

**Issue by zerotrzy** [soywod/himalaya#54]
please add gpg encryption 
and meybe small menager of keys. email without gpg is not a good idea

**Comment by soywod** [comment]
Are you talking about passwords? If so then it already supports GPG. It depends on the command you pass to the `passwd-cmd` config. If you use [`pass`](https://www.passwordstore.org/) as you password manager then it uses GPG. I hope it answers your question.

**Comment by Adonai** [comment]
Not passwords. GPG email [signing and encryption](https://en.wikipedia.org/wiki/Email_encryption). In short, what Enigmail does.

**Comment by toastal** [comment]
@soywod Without adding all of the features of GPG into the client, an MVP of allowing PGP encrypted messages to at least be piped to another tool? Currently if you try to `himalaya read $NUM` on

```
Content-Type: application/octet-stream; name="message.asc"
Content-Description: OpenPGP encrypted message
```
you will get no return.  Similar to `himalaya read $NUM | w3m -T text/html `, I would expect I could do be able to pipe the message.

```
-t, --mime-type <MIME>    MIME type to use [default: plain]  [possible values: plain, html]
```

it would seem a extra type `pgp` could be used here.

**Comment by soywod** [comment]
Sounds good to me @toastal!

**Comment by toastal** [comment]
@soywod I hope you're doing okay, man. It looks like this project got bundled for others pretty early and now you have a stream of features everyone wants.

**Comment by soywod** [comment]
I'm fine, thanks. I just have less time to spend on open-source projects because I'm preparing my moving. I should have more time within 2 weeks :)

> It looks like this project got bundled for others pretty early

What do you mean by this?

**Comment by toastal** [comment]
Similarly to https://github.com/soywod/himalaya/issues/168#issuecomment-859382562
```toml
pgp-decrypt-cmd="xxx"
pgp-encrypt-cmd="yyy"
```

**Comment by toastal** [comment]
>  It looks like this project got bundled for others pretty early

I mean now you are in the AUR, Nix, etc. and haven't yet 1.0. No worries though. Seems the roadmap is clear and you said you're doing okay!

**Comment by soywod** [comment]
Ah yes, I understand! Don't worry, the project is not dead :smile: I just need to fix personal tasks. I don't want to speed up and break everything, I prefer to improve the tool when I really have time to spend on it. Thank you for asking!

**Comment by soywod** [comment]
For reference: https://datatracker.ietf.org/doc/html/rfc3156

**Comment by soywod** [comment]
> you will get no return. Similar to `himalaya read $NUM | w3m -T text/html `, I would expect to be able to do something like `himlaya read --type pgp $NUM | keybase pgp decrypt`, etc..

I don't think this will be doable, because the encrypted part can be a multipart containing regular parts like `text/html`, `text/plain` or attachments like `image/jpeg` etc. I will have to choice to decrypt messages within himalaya.

> ```toml
> pgp-decrypt-cmd="xxx"
> pgp-encrypt-cmd="yyy"
> ```

This looks like the most flexible solution. If the `pgp-decrypt-cmd` is set and there is a `multipart/encrypted` in a message then himalaya will try to decrypt it and continue the regular parsing of parts. If the `pgp-encrypt-cmd` is set and the argument `--encrypt` is set then the message will be encrypted and put in a `multipart/encrypted`. A third hook could be added: `pgp-check-recipient-cmd` that check if the public key of the given recipient exists. This leads to a fourth hook: `pgp-auto` that could determine (based on `pgp-check-recipient-cmd`) if the message needs to be encrypted or not. What are your thoughts guys?

**Comment by soywod** [comment]
I found a really promising project: a rust implementation of the PGP standard https://github.com/rpgp/rpgp. It could be so great to use it, this way no need for hooks!

**Comment by soywod** [comment]
Just for information, I dived into the rPGP lib and I came up to those conclusions:

- It is complex to set up, but it can really improve the user experience
- A key manager is needed (I did not find any lib doing so, it will need to be developed inside himalaya)

For now, I think it is easier (and less time consuming) to go for pgp hooks. Later, when himalaya becomes stable enough, we will be able to develop a better solution. I opened a separate issue for this purpose #286.

**Comment by toastal** [comment]
This seems reasonable.
-- 
toastal ไข่ดาว | https://toast.al
PGP: 7944 74b7 d236 dab9 c9ef  e7f9 5cce 6f14 66d4 7c9e

**Comment by soywod** [comment]
Since this feature has no impact on the rest, I shipped it with the new release. This way it will be easier for people to try it. I added the `EXPERIMENTAL` tag in the wiki. Feel free to post your feedback in this issue or in a discussion channel!

**Comment by devanlooches** [comment]
So I just tried out this new feature and it works really well. I can decrypt and encrypt files. One thing that would be really nice though is to have the encrypted message appear in the message body rather than as two attachments, one of which just says the words: "version 1".

**Comment by soywod** [comment]
> One thing that would be really nice though is to have the encrypted message appear in the message body rather than as two attachments

From the RFC:

> OpenPGP encrypted data is denoted by the "multipart/encrypted" content type […] The multipart/encrypted MIME body MUST consist of exactly two body parts, the first with content type "application/pgp-encrypted".  This body contains the control information.  A message complying with this standard MUST contain a "Version: 1" field in this body.

Except if there is other parts in this RFC I did not read, I have the feeling that this is how it is supposed to be. Then, email clients interpret them the way they want. During my tests I also noticed that Thunderbird and Gmail were showing attachments. But those attachments were also there when sending encrypted messages from Thunderbird to Gmail (without himalaya).

**Comment by devanlooches** [comment]
Oh now I see what you mean. Anyway it seems to be working fine, I just wanted to point that out but now I see what you ment.
