### ISSUE TITLE
Add wiki entry about how to configure Gmail accounts

### ISSUE THREAD

**Issue by soywod** [soywod/himalaya#58]
See https://github.com/soywod/himalaya/issues/52.

**Comment by oren** [comment]
I apologize if this is trivial. Where can i see the documentation for gmail? I see this error:
```
 Cannot login to IMAP server
 ↳ No Response: Application-specific password required: https://support.google.com/accounts/answer/185833 (Failure)
```

**Comment by oren** [comment]
i guess i need to follow https://support.google.com/accounts/answer/185833...

**Comment by soywod** [comment]
Did you try this procedure? https://github.com/soywod/himalaya/issues/52#issuecomment-813100541

**Comment by soywod** [comment]
Entry added: https://github.com/soywod/himalaya/wiki/Configuration:note-for-gmail-users.
