### ISSUE TITLE
Save email upon error

### ISSUE THREAD

**Issue by AckslD** [soywod/himalaya#59]
If something goes wrong when trying to send an email it would be great if the email could be recovered in some way. For example when trying to send an email I got
```
> himalaya write              
(s)end, (d)raft, (e)dit or (q)uit? s
Sending…
Unexpected newline in header key 
```
Maybe the editor should show up again then with the editor or when typing `himalaya write` again?

**Comment by soywod** [comment]
The draft is saved in the `/tmp` directory. So theoretically I can load it back. Thanks for the feedback!

**Comment by soywod** [comment]
If a draft file is found locally, then a new prompt is shown (no matter the command `write`, `reply` or `forward`):

```
A draft was found:
(e)dit, (d)iscard or (q)uit?
```

- `Edit` opens the editor with the previous draft
- `Discard` discards the draft and continues the edition process (depending on the original command)
- `Quit` quits the program and leaves the draft untouch

**Comment by AckslD** [comment]
Awesome @soywod! Do you think it would make sense to also have for example (i)gnore which proceeds with the operating but keeps the draft?

**Comment by soywod** [comment]
Mmh I'm afraid it's not compatible with the actual system. Only one single draft can exist at the same time (the draft is overridden by the most recent command). For now, the only solution is to `Edit`, then exit the editor, then answer `r` to the next choice (which stands for `remote draft`). This way your draft is locally deleted (so you can do new actions) and remotely saved.

**Comment by AckslD** [comment]
I see, that's also fine I'd say :)
