### ISSUE TITLE
Add telescope support

### ISSUE THREAD

**Issue by AckslD** [soywod/himalaya#61]
Currently switching mailboxes in the vim-plugin gives a (long) list of choices and asking to enter a number. This is not so easy to parse if there are many mailboxes.

Maybe a better approach could be to use a floating window with the list of mailboxes that can be navigated using `jk`. This could even give a preview of the mailbox which would be supercool :) For example how [lspsaga](https://github.com/glepnir/lspsaga.nvim) handles [references](https://user-images.githubusercontent.com/41671631/107140076-ae77ec00-695a-11eb-8329-0b9d8361bfeb.gif).

**Comment by soywod** [comment]
Have a look at https://github.com/junegunn/fzf, the Vim plugin supports it. This way you can select your mailbox with fuzzy finding, which is quite appreciable ;)

**Comment by AckslD** [comment]
Oh nice! :) I started using telescope instead of fzf. Would you be interested in also supporting telescope? I could take a look at that and open a PR if that's something you would be interested in

**Comment by soywod** [comment]
You are talking about https://github.com/nvim-telescope/telescope.nvim? I didn't know about this, looks great, I will give a shot! Sure for the support, feel free to propose a PR if you want!

**Comment by soywod** [comment]
Telescope support added in 442dc457b57c7b7563b8cf0fdb6786fc529886b3 :tada:

**Comment by AckslD** [comment]
Awesome @soywod!
