### ISSUE TITLE
Ensure that SMTP connection failures do not cause messages to drop

### ISSUE THREAD

**Issue by biox** [soywod/himalaya#65]
Currently, if himalaya fails to connect or authenticate to the remote SMTP server, it causes the written message to be discarded with no user recourse. I propose re-opening the `(s)end, (d)raft, (e)dit or (q)uit?` dialogue, so that the user may select "edit" in order to save their written message. Alternatively, you could prompt the user to save their drafted message to disk somewhere.

**Comment by soywod** [comment]
Duplicate #59
