### ISSUE TITLE
Non-monospaced unicode characters break the inbox view

### ISSUE THREAD

**Issue by coastalwhite** [soywod/himalaya#71]
Receiving a mail with a non standard width Unicode character in the inbox view breaks line-alignment.

Mostly, when receiving emojis in the subject of an email, the line used for that mail will be longer than was expected. As can be seen in the following image:

![image](https://user-images.githubusercontent.com/6944009/113858121-a7772980-97a3-11eb-91f6-ed536780c223.png)

**Comment by soywod** [comment]
I noticed also this bug recently, I will investigate. Thanks for the feedback!

**Comment by soywod** [comment]
Unicode management seems to be really a pain. Thankfully I found this wonderful crate that does exactly what is needed: https://docs.rs/unicode-width/0.1.8/unicode_width/. It's fixed on master, it will be fixed within the next release!

**Comment by soywod** [comment]
Added in [v0.2.3](https://github.com/soywod/himalaya/releases/tag/v0.2.3) :tada:
