### ISSUE TITLE
Refactor the way output works

### ISSUE THREAD

**Issue by srid** [soywod/himalaya#74]
I use the following script to bulk move emails to another folder:

```bash
himalaya -o json search subject Stripe | jq '.[].uid' | xargs -n 1 -I {} himalaya move {} Folders/FinanceLog
```

This script doesn't output anything, so I have no way of knowing the list of messages that just got moved by that command (that I constructed on the fly). I can script the logging manually, but it would be more convenient if the CLI had an option to log all *mutable actions* that himalaya takes on my mail account.

**Comment by soywod** [comment]
In fact the `move` command (as well as other commands like `copy`, `delete` etc) should display a log by default (without any verbose mode). I prefer to introduce a `--silent` or `--quiet` flag to disable output instead.

**Comment by soywod** [comment]
Logs added for `copy`, `move` and `delete` commands + add a `--silent` flag to disable them. It will be added to the next release!

**Comment by srid** [comment]
Should `--silent` be ignored in some commands? For eg., both `h --silent` and `h -o json --silent` outputs nothing, but `h` and `h -o json` normally would output the list of messages. 

Perhaps it would be helpful to distinguish between two kinds of outputs: "content" vs "logging". And use `--silent` only suppress the later kind.

**Comment by soywod** [comment]
It's a good point indeed, I like the idea!

**Comment by soywod** [comment]
> Perhaps it would be helpful to distinguish between two kinds of outputs: "content" vs "logging".

In fact it depends on the ouptut type. For `text` then indeed you have content and logging. But for `json` you can only have content. I have an idea on how to implement this, I let you know!

**Comment by srid** [comment]
Another idea that comes to mind is to send all logging output to `stderr`, leaving regular output to `stdout`. Then quiet behaviour can also be achieved using `himalaya ... 2> /dev/null`. But then I wonder if there are better ways.

**Comment by soywod** [comment]
I am not so fan of this idea, it sounds a bit "hakcy". The `stderr` should be kept for errors only. I prefer to explicitly expose log levels to user via the CLI args. I have sth working based on the [log](https://docs.rs/log/0.4.14/log/) crate and the [env_logger](https://docs.rs/env_logger/0.8.3/env_logger/) crate:

- A new arg will be introduced (and will replace `--silent`): `--log` or `-l` that defines the log level (one of `error`, `warn`, `info`, `debug`, `trace` as defined in the log crate)
- The `PLAIN` output will show logs depending on the given log level (`info` is the standard default one)
- The `JSON` output will show only `info` and `error` logs:
  - `info` logs are serialized to JSON strings
  - `error` logs remains plain strings (this way, any client will know that the command failed if he can't parse the JSON)
- `error` logs are sent to the `stderr` channel, and all other logs are sent to the `stdout` one

**Comment by soywod** [comment]
Added in [v0.2.4](https://github.com/soywod/himalaya/releases/tag/v0.2.4) :tada:
