### ISSUE TITLE
"NextPart: EOF" error when moving DigitalOcean emails

### ISSUE THREAD

**Issue by srid** [soywod/himalaya#75]
For some reason, I cannot move emails from DigitalOcean.

```
❯ ~/h  search subject DigitalOcean 

UID |FLAGS |SUBJECT                                                |SENDER       |DATE                
14  |      |[DigitalOcean] Your January 2021 invoice is available  |DigitalOcean |2021-01-31 22:16:42 
11  |      |[DigitalOcean] Your February 2021 invoice is available |DigitalOcean |2021-03-01 09:01:43 
7   |      |[DigitalOcean] Your March 2021 invoice is available    |DigitalOcean |2021-04-01 02:22:07 


❯ ~/h -o json search subject DigitalOcean | jq '.[].uid' | xargs -n 1 -I {} ~/h move {} Folders/FinanceLog
Cannot append message to `Folders/FinanceLog`
 ↳ No Response: failed to create new parser: multipart: NextPart: EOF
Cannot append message to `Folders/FinanceLog`
 ↳ No Response: failed to create new parser: multipart: NextPart: EOF
Cannot append message to `Folders/FinanceLog`
 ↳ No Response: failed to create new parser: multipart: NextPart: EOF

❯ 
```

(Same behaviour with "search from DigitalOcean".)

I can read an individual message using `himalaya read 14`, however.

**Comment by soywod** [comment]
It looks like there is an issue with the mail itself. Do you think you can share the raw mail with sensitive data hidden?

**Comment by soywod** [comment]
I noticed that when I `copy` or `move` a mail, the attachments are lost. It may be related to your problem. I will investigate.

**Comment by soywod** [comment]
Indeed, some part where missing when I was copying / moving messages. I fixed this issue, it should be fixed in the next release. Feel free to reopen if the problem persists after the release. Thanks for the feedback!

**Comment by soywod** [comment]
Added in [v0.2.3](https://github.com/soywod/himalaya/releases/tag/v0.2.3) :tada:
