### ISSUE TITLE
Save draft somewhere when sending fails

### ISSUE THREAD

**Issue by srid** [soywod/himalaya#77]
I tried to send an email, but it failed. 

```
❯ EDITOR=nvim h write
(s)end, (d)raft, (e)dit or (q)uit? s
Sending…
internal client error: timed out waiting for connection: Connection error: Could not connect
```

The email text is no longer accessible to me, but himalaya should at least print the path to the email file, and maybe also allow me to retry it (eg: `h write --input=email-draft.txt`).

**Comment by soywod** [comment]
Duplicate https://github.com/soywod/himalaya/issues/59.
