### ISSUE TITLE
Allow send to accept message in stdin

### ISSUE THREAD

**Issue by srid** [soywod/himalaya#78]
By the way, just running the send command (no arguments, or with `--` but nothing after that) crashes himalaya:

```
❯ h send
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/msg/cli.rs:466:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm opening this issue to request the following feature:

```
❯ h send --stdin < /tmp/himalaya-draft.mail
```

Basically, allow specifying the email message in stdin. This would be useful for #59 as well.

**Comment by srid** [comment]
Incidentally, specifying that draft as an argument doesn't work:

```
❯ h send -- $(cat /tmp/himalaya-draft.mail)
missing source address, invalid envelope

❯ cat /tmp/himalaya-draft.mail 
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit
From: Sridhar Ratnakumar <hey@srid.ca>
To: srid@srid.ca
Subject:  From himalaya!

Test

--
cheers,-srid
```

I guess this might be something to do with the way shell passes arguments with multiple lines.

**Comment by soywod** [comment]
In fact, there is some "hidden" commands that are only used by UIs. The `send` is part of them. I need to find a way to not show them in the doc. Later, indeed, a `--stdin` arg could be interesting!

**Comment by soywod** [comment]
Added on master. I also updated [the wiki](https://github.com/soywod/himalaya/wiki/Usage:msg:send). Both arg and stdin can be used to send a message:

```sh
himalaya send -- From: test@mail.com\r\n\r\nHello
himalaya send < my-template.mail
cat my-template.mail | himalaya send
```
