### ISSUE TITLE
A command to retrieve the raw message

### ISSUE THREAD

**Issue by srid** [soywod/himalaya#79]
`h read` only returns the text body, but it would be useful to have a command that returns the entire raw message. In JSON mode (`-o json`), the output could be in a structured form, instead of just dumping the raw email message.

This would be analogous to `h write` which does take a raw message.

**Comment by soywod** [comment]
I totally agree. It should not be so hard, since I have the raw message in memory!

**Comment by srid** [comment]
As an aside, I like the `template` command. 

I plan to use himalaya mostly in scripts, and being able to even fill in "template variables" would be handy in that workflow. For eg.,

```
echo Ping | h template new --to=user@example.com --subject=Hello --body-stdin | h send --stdin
```

**Comment by soywod** [comment]
First I wanted to add a new type to the arg `--mime-type`. But it's not so clear in which category we should put this "raw" mode (`text/plain`? `application/octet-stream`?). So I decided to introduce a new flag `--raw` that returns the raw message as `UTF8` encoded string. Let me know what you think about it.

**Comment by soywod** [comment]
Added in [v0.2.4](https://github.com/soywod/himalaya/releases/tag/v0.2.4) :tada:
