### ISSUE TITLE
Improve the template command

### ISSUE THREAD

**Issue by soywod** [soywod/himalaya#80]
As an aside, I like the `template` command. 

I plan to use himalaya mostly in scripts, and being able to even fill in "template variables" would be handy in that workflow. For eg.,

```
echo Ping | h template new --to=user@example.com --subject=Hello --body-stdin | h send --stdin
```

_Originally posted by @srid in https://github.com/soywod/himalaya/issues/79#issuecomment-815982827_

**Comment by srid** [comment]
Being able to set custom headers (eg: when sending from [rss-watch](https://lib.rs/crates/rss-watch), I'd like to set some header so as to be able to filter rss emails to be sent to some folder) would be nice too.

**Comment by soywod** [comment]
> Being able to set custom headers (...) would be nice too.

How do you see this? Sth *alla* cURL?

```sh
himalaya template new --to user@example.com --subject Hello --header "key: val" --header "key: val"
```

**Comment by soywod** [comment]
I refactored the `Template` system, it is way more flexible now. Here the list of the new options you can use to override parts of the template:

- `--subject`
- `--from`
- `--body`
- `--signature`

Those ones can be used multiple times:

- `--to`
- `--cc`
- `--bcc`
- `--header` (it should follow the format KEY: VAL, for eg: `--header "TheKey: TheVal"`)

I just miss the body via stdin + tests + doc and I should be able to release it. I let you know @srid!

**Comment by srid** [comment]
Nice! I haven't been using `himalaya` for a while (doing other things now) but I intend to eventually come back to it so as to customize and finalize a new email-based workflow for me (eg: get rss via email, then do a CLI workflow for reading and archiving links; then GTD, etc.).

**Comment by soywod** [comment]
Great :)

**Comment by soywod** [comment]
Added on master, it will be included in the next release!
