### ISSUE TITLE
Init CI on master + tests

### ISSUE THREAD

**Issue by srid** [soywod/himalaya#81]
Both nix and non-nix examples here:

https://github.com/srid/bouncy/tree/master/.github/workflows

**Comment by soywod** [comment]
Well, CI makes sens when you have tests to run. Which I don't have for now :laughing:. I keep this issue for later.

**Comment by soywod** [comment]
I added 2 workflows: one for tests, one for nix (thanks for your link, it was useful). Feel free to adjust!
