### ISSUE TITLE
delete/copy behavior

### ISSUE THREAD

**Issue by remche** [soywod/himalaya#83]
After deleting (or moving) a message, next call to `himalaya list` still shows the message... but Thunderbird won't. Using Thunderbird `Compact` action update the mailboxes.

I'm not fluent with IMAP protocol but I assume it's the way himalaya and other client use flags. An entry in the doc could be helpful, seems confusing for new users !

**Comment by soywod** [comment]
It's not the behaviour I'm expecting when copying or moving a mail. It's definitely a bug. Thanks for the feedback!

**Comment by soywod** [comment]
In fact I needed to trigger an `expunge` after those commands, so the IMAP server deletes mails with the `\Deleted` flag. It's fixed on master, it will be fixed in the next release!

**Comment by soywod** [comment]
Fixed in [v0.2.5](https://github.com/soywod/himalaya/releases/tag/v0.2.5) :tada:
