### ISSUE TITLE
Ignore self-signed certificate option

### ISSUE THREAD

**Issue by remche** [soywod/himalaya#84]
Enabling self-signed certificates (and/or non-encrypted connections) would allow to play with test servers like [GreenMail](https://github.com/greenmail-mail-test/greenmail) (and write some CI functional tests ?).

**Comment by soywod** [comment]
I'm not sure this is related to Himalaya. A self-signed cert can be trusted from the OS side, like in [this article](https://iptq.io/setup/command-line-email-with-aerc/#setting-up-aerc-with-protonmail):

```sh
sudo trust anchor --store self-signed.crt
```

**Comment by ibotty** [comment]
I don't know how to use `trust` when I am not system admin.  It would be great to allow that use case.

**Comment by soywod** [comment]
We could attach a new property to the config but it requires some work. This is clearly not a priority for the `v1`. I would advise to make your system trust the certs for now. Feel free to contribute if you need this feature :wink:

**Comment by remche** [comment]
My use case is mainly for testing with greenmail which generates a new cert at each run.
I might take the opportunity to learn rust ;)

**Comment by soywod** [comment]
With great pleasure :wink: feel free to use the [discussion feature](https://github.com/soywod/himalaya/discussions) if needed!
