### ISSUE TITLE
Allow specifying a custom config location

### ISSUE THREAD

**Issue by srid** [soywod/himalaya#86]
This would come in handy for a scenario like https://github.com/soywod/himalaya/pull/76#issuecomment-816871545 

```
himalaya --config-file=~/dotfiles/himalaya.conf
```

or,

```
HIMALAYA_CONFIG_FILE=~/dotfiles/himalaya.config himalaya
```

**Comment by soywod** [comment]
I introduced the argument `--config|-c` that forces the app to use a specific path for the config file.
