### ISSUE TITLE
Unable to send emails when using ProtonMail bridge

### ISSUE THREAD

**Issue by srid** [soywod/himalaya#87]
([protonmail bridge](https://github.com/ProtonMail/proton-bridge) runs a _local_ IMAP server)

Listing and reading emails work, but for some reason I cannot send any emails using himalaya.

```
❯ h -l trace  write
Logger initialized
Output format: PLAIN
Log level: TRACE
Subcommand matched: write
(s)end, (d)raft, (e)dit or (q)uit? s
Sending message…
Connection error: Could not connect
Connection error: Could not connect
Connection error: Could not connect
Connection error: Could not connect
Connection error: Could not connect
Connection error: Could not connect
Connection error: Could not connect
internal client error: timed out waiting for connection: Connection error: Could not connect
```

There is nothing in the protonmail-bridge log, so I suspect the request is not even reaching it.

Other email clients work. 

Let me know if there is a way to provide more diagnostic info.

**Comment by soywod** [comment]
I think it's linked to https://github.com/soywod/himalaya/issues/60. I tried myself the protonmail bridge and I was not able to reproduce :disappointed: so I have not a single clue on how to fix this.

**Comment by srid** [comment]
Perhaps something to do with timeout configuration?

https://protonmail.com/support/knowledge-base/thunderbird-connection-server-timed-error/

> In Thunderbird, you may receive a “connection to server timed out” error when sending or receiving a message. Connection timeout errors occur when the server takes too long to respond to a request from your device.
> 
> You may be able to prevent this error by increasing the length of time the email client will wait for a response from the server.

**Comment by soywod** [comment]
I can try to increase the timeout for the next release and see!

**Comment by srid** [comment]
Shouldn't this include `smtp_port`?

https://github.com/soywod/himalaya/blob/926f476194a66d6854d302f9f846e71b7880b72c/src/smtp.rs#L24-L28

**Comment by srid** [comment]
Yup, that fixes it! Now I can move forward with scripting more with himalaya :-)

**Comment by soywod** [comment]
> Shouldn't this include `smtp_port`?

Yes indeed... Nice catch dude, it was a tricky one!
