### ISSUE TITLE
Cargo.lock is not up-to-date

### ISSUE THREAD

**Issue by orhun** [soywod/himalaya#88]
Hey, [AUR](https://aur.archlinux.org/packages/himalaya/) maintainer here.

I was trying to build version `0.2.4` of `himalaya` and faced the following issue:

```
    Updating crates.io index
error: the lock file /build/himalaya/src/himalaya-0.2.4/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, use the --offline flag.
```

The thing is I have to use `--locked` flag for the [reproducibility](https://reproducible-builds.org) of Rust packages. ([Rust packaging guidelines](https://wiki.archlinux.org/index.php/Rust_package_guidelines#Building) also mentions that) So I guess after `0.2.3`, `Cargo.lock` wasn't updated along with `Cargo.toml` and that's why I'm facing this problem.

With the upcoming releases you can bump the version in `Cargo.toml` and run `cargo build` to update the `Cargo.lock` so that it will be up-to-date. Also you can use `--locked` flag on your CI/CD to make sure everything's fine.

I just wanted to make you aware of this issue :) I might have to pass `0.2.4` for the AUR package and wait for the next release.

**Comment by soywod** [comment]
It looks like my mistake has bigger consequences than I thought :laughing: I will not forget the `cargo build` next time :+1: I will try to build a new release this weekend. Thanks!
