### ISSUE TITLE
Add ability to change account

### ISSUE THREAD

**Issue by maricn** [soywod/himalaya#91]
Hi there, great work on the tool and vim plugin.

It would be awesome to have a plugin shortcut to change the accounts used in vim plugin. Currently it seems to be possible only to move around mailboxes and pages within the default account from vim.

**Comment by soywod** [comment]
Yes, it's part of the feature I would like to implement. Thanks for pointing it out!

**Comment by soywod** [comment]
In fact it could be nice to list available accounts. A bit like for mailboxes. But this requires to also change the CLI!

**Comment by jakeschurch** [comment]
hey @soywod  -- I would also really be interested in using this feature! how is this going so far?

**Comment by soywod** [comment]
I am working on https://github.com/soywod/himalaya/issues/80 these days. As soon as I finish I will take care of this one :smiley:

**Comment by MatthiasGrandl** [comment]
@soywod Would it be feasible to have the option of a "unified inbox"? Basically just list all inboxes of my account at once and fuzzy search through it (with the VIM plugin).

**Comment by soywod** [comment]
Is it what you are looking for? https://github.com/soywod/himalaya/tree/master/vim#list-mailboxes.
For now there is only 2 integrations (fzf and telescope).

**Comment by MatthiasGrandl** [comment]
@soywod no what I am asking is whether you can display all emails in your inbox across multiple accounts. So let's say I have a gmail work account and a personal mail server, I want to display both inboxes as one.

The integrations are great, very much appreciate the telescope one :)

**Comment by soywod** [comment]
> @soywod no what I am asking is whether you can display all emails in your inbox across multiple accounts. So let's say I have a gmail work account and a personal mail server, I want to display both inboxes as one.

I understand now. It could be interesting indeed, but I'm afraid the CLI is not designed for such a thing right now. Maybe sth to consider after the v1!

> The integrations are great, very much appreciate the telescope one :)

You can thank @AckslD, he did a lot for this feature :wink:

**Comment by soywod** [comment]
I start to work on this feature, I let you know when I have sth to propose!

**Comment by MatthiasGrandl** [comment]
@soywod I think a good start would be to just be able to specify the account with `:Himalaya account=gmail` unless that is already possible somehow and I missed it. Being able to do that, I could just use which-key to have inidividual shortcuts with a nice indicator for my accounts.

**Comment by soywod** [comment]
The account is now attached to the Vim session (like the mbox and the pagination). You can change the account by adding a parameter to the command: `:Himalaya gmail`. It is available on master, so you should get the feature by upgrading the plugin. I should also release soon the next CLI version.

**Comment by soywod** [comment]
[`v0.4.0`](https://github.com/soywod/himalaya/releases/tag/v0.4.0) released :tada:
