### ISSUE TITLE
Add an option to disable the Telescope preview

### ISSUE THREAD

**Issue by soywod** [soywod/himalaya#92]
The preview in unusable when Himalaya connects to a remote IMAP server (delay between searches are insane). We need to find a way to disable this feature with a flag.

**Comment by AckslD** [comment]
Sounds good @soywod! How would you prefer to configure this? I don't see if there are already configuration options. For example we could have the user set the global value `g:himalaya_enable_telescope_preview` (`vim.g.himalaya_enable_telescope_preview` for neovim). Perhaps having if off by default is better than on? Furthermore, maybe the user could also then choose the preferred way of searching, i.e. telescope, fzf or through direct choice. What do you think?

Maybe while doing this it would also be good to add an option for if the default keybindings should be configured or not?

**Comment by soywod** [comment]
Sounds great! I would name it sth like `g:himalaya_telescope_preview_enabled` since it's a flag. An other option for choosing the search provider is also great. It's not a priority, but if you feel motivated for, feel free to propose :smiley:

> Maybe while doing this it would also be good to add an option for if the default keybindings should be configured or not?

I'm not sure to understand this last one. If you talk about keybinds in general then it's already configurable. See https://github.com/soywod/himalaya/tree/master/vim. For example to change the default `gm` keybind, you can do sth like `nmap <leader>m <plug>(himalaya-mbox-input)`.

**Comment by AckslD** [comment]
Cool! I'll make an attempt to add this and share it to see what you think.

What I meant regarding keybinds is that currently the default keybindings are always configured, even if you set `nmap <leader>m <plug>(himalaya-mbox-input)` you will still have `nmap gm <plug>(himalaya-mbox-input)`, which someone might not want. Unless I've gotten this wrong. So maybe it's nice to have e.g. `g:himalaya_default_keybinds_disabled`. This is separate from the above issue though :)

**Comment by soywod** [comment]
> even if you set `nmap <leader>m <plug>(himalaya-mbox-input)` you will still have `nmap gm <plug>(himalaya-mbox-input)`

I think this is a bug, it should override the default one. I did on purpose to avoid having a keybinds variable. I will investigate this point.

**Comment by AckslD** [comment]
I haven't actually tried this but thought this was the case by looking at the code since if the code does e.g. `nmap lhs1 rhs1` and the user then does `nmap lhs2 rhs1` it does not remove the mapping of `lhs1` which would only be overridden if the user did `nmap lhs1 rhs2` which is something else. But I might be misunderstanding something.

**Comment by soywod** [comment]
I just tried, I confirm that it overrides well the default mapping. It's because I declared a special mapping `<plug>`, see `:h <plug>`. So we can forget this last point :wink:

**Comment by AckslD** [comment]
Ooh, didn't know that `<plug>` worked like that :) Sorry for the confusion!
