### ISSUE TITLE
Vim plugin broken?

### ISSUE THREAD

**Issue by AckslD** [soywod/himalaya#93]
In latest master it seems the vim plugin is broken. When running `:Himalaya` I get:
```
Vim(for):E730: using List as a String
```

Maybe something changed in the cli that now breaks the vim plugin. I haven't digged to deep but I suspect the warning comes from [this line](https://github.com/soywod/himalaya/blob/master/vim/autoload/himalaya/shared/cli.vim#L15). Since if I print `res` directly after it's being returned by `system(` it looks something like
```
[{"uid":xxx,"flags":["nonjunk"],"subject":"xxx","sender":"xxx","date":"2021-04-12 17:43:04"}]
```
which I guess fails at the line `res.response` since it doesn't have that field. And then when it goes to the the line with `split(res, '\n')` it's not a string anymore after `res = eval(res)`.

**Comment by soywod** [comment]
Which CLI version do you have? Indeed the API slightly changed. All response are wrapped in a `{"response": ...}` so that strings can be received (like info msgs).

**Comment by AckslD** [comment]
Hmm strange, I was on 0.2.2 even though yay said I was on latest of [himalaya-git](https://aur.archlinux.org/packages/himalaya-git/). Anyway, reinstalled and now on 0.2.5 things indeed work again 👍
