### ISSUE TITLE
Add default page-size to config

### ISSUE THREAD

**Issue by srid** [soywod/himalaya#96]
I used to think that himalaya had a bug when it displayed only the last few messages, until I learned about the -s flag.

10 is also an unusually low number IMO. Is there any reason why 10 was chosen?

**Comment by soywod** [comment]
One of the main purpose of Himalaya is to interact with your mais through the terminal. I thought that the 10 last msgs are a good compromise. It fits well the screen, it's not too slow. But for a scripting purpose I agree it's not enough. The default page size can be overriden in the config though.

**Comment by srid** [comment]
>  I can make the default page size customizable via the config though, what do you think?

Yea, that'll work.

**Comment by soywod** [comment]
Added in 10d2982.

**Comment by soywod** [comment]
I introduced a new key in the configuration called `default-page-size`, which accepts an optional number (default: 10). It can be set at the top level (global) or by account. It is overridden by the arg `--page-size|-s`. Setting a page size = 0 disables the pagination and shows all the results available. See the [wiki](https://github.com/soywod/himalaya/wiki/Configuration) for more information.
