### ISSUE TITLE
Add an entry in the wiki about message composition structure

### ISSUE THREAD

**Issue by remche** [soywod/himalaya#98]
When trying to send a mail I got  `Unexpected newline in header key`. 
I tried with neovim and micro editors. Nothing fancy in the faulty mail...

**Comment by soywod** [comment]
Can you share the mail you try to send? This may be caused by a missing new line between headers and body, or a body without new line.

**Comment by remche** [comment]
oops... You're right I did not put a newline between headers and body. Sorry for the noise ! :sweat: 
Some warning could be helpful for incompetent users ;)

**Comment by soywod** [comment]
Indeed, a tiny notice in the wiki could be great. Thanks for the feedback!

**Comment by soywod** [comment]
Added at https://github.com/soywod/himalaya/wiki/Usage:msg:write.
